import { get, list } from '@vercel/blob';

const auths = [
  ...(process.env.VERCEL_OIDC_TOKEN && process.env.BLOB_STORE_ID ? [{ oidcToken: process.env.VERCEL_OIDC_TOKEN, storeId: process.env.BLOB_STORE_ID }] : []),
  ...(process.env.BLOB_READ_WRITE_TOKEN ? [{ token: process.env.BLOB_READ_WRITE_TOKEN }] : []),
];
const header=(req:any,n:string)=>req?.headers?.get?n&&req.headers.get(n)||'':req?.headers?.[n.toLowerCase()]||'';
const authorized=(req:any)=>Boolean(process.env.DASHBOARD_PASSWORD&&header(req,'authorization')===`Bearer ${process.env.DASHBOARD_PASSWORD}`);
const send=(res:any,status:number,body:unknown)=>res.status(status).setHeader('Cache-Control','no-store').json(body);
async function blob<T>(fn:(a:any)=>Promise<T>){let last:any;for(const a of [{},...auths])try{return await fn(a)}catch(e){last=e}throw last}
async function read(url:string){const r:any=await blob(a=>get(url,{access:'private',...a}));return r?.stream?await new Response(r.stream).json():null}
function phone(v:string){const d=String(v||'').replace(/\D/g,'');return d.length===10?`91${d}`:d}
function money(v:any){return v==null?'':String(v)}
async function sendWhatsApp(to:string,text:string){const token=process.env.WHATSAPP_ACCESS_TOKEN||'';const id=process.env.WHATSAPP_PHONE_NUMBER_ID||'';if(!token||!id||!to)return {sent:false,reason:'WhatsApp credentials or customer phone missing'};const version=process.env.WHATSAPP_GRAPH_VERSION||'v23.0';const r=await fetch(`https://graph.facebook.com/${version}/${id}/messages`,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({messaging_product:'whatsapp',to,type:'text',text:{preview_url:false,body:text}})});if(!r.ok)return {sent:false,reason:await r.text()};return {sent:true}}
async function matches(lead:any){try{const r:any=await blob(a=>list({prefix:'crm/properties/',...a}));const all=(await Promise.all(r.blobs.map(async(b:any)=>{try{return await read(b.url)}catch{return null}}))).filter(Boolean);const loc=String(lead.location||'').toLowerCase();const type=String(lead.property_type||'').toLowerCase();const bhk=String(lead.bhk||'').toLowerCase();return all.filter((p:any)=>String(p.status||'Available').toLowerCase()==='available').filter((p:any)=>!loc||String(p.location||'').toLowerCase().includes(loc)||loc.includes(String(p.location||'').toLowerCase())).filter((p:any)=>!type||String(p.type||p.propertyType||'').toLowerCase().includes(type)).filter((p:any)=>!bhk||String(p.bedrooms||p.bhk||'').toLowerCase().includes(bhk)).slice(0,3)}catch{return []}}
export default async function handler(req:any,res:any){if(req.method!=='POST')return send(res,405,{error:'Method not allowed'});if(!authorized(req))return send(res,401,{error:'Unauthorized'});try{const b=req.body&&typeof req.body==='object'?req.body:JSON.parse(String(req.body||'{}'));const name=String(b.name||'Customer').trim();const customerPhone=phone(String(b.phone||''));if(!customerPhone)return send(res,400,{error:'Customer phone is required'});const lead={name,phone:customerPhone,location:String(b.location||''),property_type:String(b.property_type||''),budget:String(b.budget||''),timeline:String(b.timeline||''),property_name:String(b.property_name||'')};const found=await matches(lead);const lines=found.map((p:any,i:number)=>`${i+1}. ${p.title||p.name||'Property'} — ${p.location||''}${p.price?' — '+money(p.price):''}${p.bedrooms?' — '+p.bedrooms+' BHK':''}`).join('\n');const text=`Hi ${name}, 👋\n\nThank you for contacting ANJANAY HEIGHTS. Your property requirement has been received.\n\n${found.length?`We found these available options matching your requirement:\n${lines}\n\nOur property consultant will contact you shortly to confirm availability and arrange a site visit.`:'Our property consultant will contact you shortly with suitable available options and confirm current availability.'}\n\nReply YES if you want a site visit, or send your preferred date/time.\n\nANJANAY HEIGHTS\nNoida • Greater Noida • NCR`;const result=await sendWhatsApp(customerPhone,text);return send(res,200,{ok:true,whatsapp:result,matchedProperties:found.map((p:any)=>({id:p.id,title:p.title||p.name,location:p.location,price:p.price,bedrooms:p.bedrooms||p.bhk}))})}catch(e){console.error('customer whatsapp error',e);return send(res,500,{error:'Unable to send customer WhatsApp acknowledgement.'})}}