import { get, head, put } from '@vercel/blob';
import { createHmac } from 'node:crypto';
const PATH='crm/payment-collections.json';
const candidates=[...(process.env.VERCEL_OIDC_TOKEN&&process.env.BLOB_STORE_ID?[{oidcToken:process.env.VERCEL_OIDC_TOKEN,storeId:process.env.BLOB_STORE_ID}]:[]),...(process.env.BLOB_READ_WRITE_TOKEN?[{token:process.env.BLOB_READ_WRITE_TOKEN}]:[])];
function h(req:any,n:string){const x=req?.headers;if(x&&typeof x.get==='function')return x.get(n)||'';return x?.[n.toLowerCase()]||x?.[n]||''}
function ok(req:any){const p=process.env.DASHBOARD_PASSWORD||'';const t=p?createHmac('sha256',p).update('anjanay-heights-crm-session').digest('hex'):'';return Boolean((p&&h(req,'authorization')===`Bearer ${p}`)||(t&&String(h(req,'cookie')).includes(`ah_crm_session=${t}`)))}
function authErr(e:any){return /access denied|credentials|unauthorized|forbidden|valid token/i.test(`${e?.name||''} ${e?.message||''}`)}
async function blob<T>(fn:(a:any)=>Promise<T>){let last:any;for(const a of [{},...candidates])try{return await fn(a)}catch(e){last=e;if(!authErr(e))throw e}throw last}
async function read(){try{const i:any=await blob(a=>head(PATH,a));const r:any=await blob(a=>get(i.url,{access:'private',useCache:false,...a}));return {data:await new Response(r.stream).json(),etag:i.etag}}catch(e:any){if(e?.status===404||/not found|BlobNotFound/i.test(`${e?.name||''} ${e?.message||''}`))return {data:{},etag:undefined};throw e}}
async function write(data:any,etag?:string){return blob(a=>put(PATH,JSON.stringify(data),{access:'private',addRandomSuffix:false,allowOverwrite:true,contentType:'application/json',...(etag?{ifMatch:etag}:{}),...a}))}
function dueState(due?:string,paid?:string){if(paid)return 'PAID';if(!due)return 'NO DUE DATE';const d=new Date(`${due}T00:00:00+05:30`).getTime();const now=Date.now();const days=Math.ceil((d-now)/86400000);if(days<0)return `OVERDUE ${Math.abs(days)}D`;if(days===0)return 'DUE TODAY';if(days<=3)return `DUE ${days}D`;if(days<=7)return `DUE ${days}D`;return 'UPCOMING'}
export default async function handler(req:any,res:any){if(!ok(req))return res.status(401).json({error:'Unauthorized'});try{if(req.method==='GET'){const x=await read();const records=Object.entries((x.data||{}) as Record<string,any>).map(([leadId,v]:any)=>({...v,leadId,state:dueState(v.dueDate,v.paidDate)}));const overdue=records.filter(x=>x.state.startsWith('OVERDUE'));const due=records.filter(x=>['DUE TODAY','DUE 1D','DUE 2D','DUE 3D'].includes(x.state));return res.status(200).setHeader('Cache-Control','no-store').json({records,overdue,due,counts:{total:records.length,overdue:overdue.length,due:due.length,paid:records.filter(x=>x.state==='PAID').length}})}if(req.method==='POST'){const b=req.body&&typeof req.body==='object'?req.body:{};const leadId=String(b.leadId||'').trim();if(!leadId)return res.status(400).json({error:'leadId is required'});for(let attempt=0;attempt<3;attempt++){const s=await read();const all:Record<string,any>=s.data||{};const incoming=b.payment&&typeof b.payment==='object'?b.payment:{};const record:any={...(all[leadId]||{}),...incoming,updatedAt:new Date().toISOString()};for(const k of Object.keys(record))record[k]=String(record[k]??'').slice(0,2000);record.state=dueState(record.dueDate,record.paidDate);all[leadId]=record;try{await write(all,s.etag);return res.status(200).json({ok:true,leadId,payment:record})}catch(e:any){if(!/precondition|etag/i.test(String(e?.message||''))||attempt===2)throw e}}}return res.status(405).json({error:'Method not allowed'})}catch(e){console.error('payment-collections error',e);return res.status(500).json({error:'Unable to access payment collection storage.'})}}