import { get, head, put } from '@vercel/blob';
import { createHmac } from 'node:crypto';
const PATH='crm/payment-escalation.json';
const auths=[...(process.env.VERCEL_OIDC_TOKEN&&process.env.BLOB_STORE_ID?[{oidcToken:process.env.VERCEL_OIDC_TOKEN,storeId:process.env.BLOB_STORE_ID}]:[]),...(process.env.BLOB_READ_WRITE_TOKEN?[{token:process.env.BLOB_READ_WRITE_TOKEN}]:[])];
function h(r:any,n:string){const x=r?.headers;if(x&&typeof x.get==='function')return x.get(n)||'';return x?.[n.toLowerCase()]||x?.[n]||''}
function ok(r:any){const p=process.env.DASHBOARD_PASSWORD||'',s=p?createHmac('sha256',p).update('anjanay-heights-crm-session').digest('hex'):'';return Boolean((p&&h(r,'authorization')===`Bearer ${p}`)||(s&&String(h(r,'cookie')).includes(`ah_crm_session=${s}`)))}
async function wa<T>(fn:(a:any)=>Promise<T>){let last:any;for(const a of [{},...auths]){try{return await fn(a)}catch(e){last=e;if(!/access denied|credentials|unauthorized|forbidden|valid token/i.test(`${(e as any)?.name||''} ${(e as any)?.message||''}`))throw e}}throw last}
async function read(){try{const i:any=await wa(a=>head(PATH,a));const x:any=await wa(a=>get(i.url,{access:'private',useCache:false,...a}));return{data:await new Response(x.stream).json(),etag:i.etag}}catch(e:any){if(e?.status===404||/not found|BlobNotFound/i.test(`${e?.name||''} ${e?.message||''}`))return{data:{},etag:undefined};throw e}}
async function write(d:any,e?:string){return wa(a=>put(PATH,JSON.stringify(d),{access:'private',addRandomSuffix:false,allowOverwrite:true,contentType:'application/json',...(e?{ifMatch:e}:{}),...a}))}
function dateOnly(v:any){const d=new Date(String(v||''));return Number.isNaN(d.getTime())?null:new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth(),d.getUTCDate()))}
export default async function handler(req:any,res:any){if(!ok(req))return res.status(401).json({error:'Unauthorized'});try{const metaRes=await fetch(`${process.env.VERCEL_URL?`https://${process.env.VERCEL_URL}`:''}/api/lead-meta`,{headers:{authorization:h(req,'authorization'),cookie:h(req,'cookie')}});const metaJson=await metaRes.json();const meta=metaJson.meta||{};const snap=await read();const records=snap.data||{};const today=dateOnly(new Date());const queue:any[]=[];for(const [leadId,m] of Object.entries(meta) as any){const b=records[leadId];if(!b?.nextPaymentDate||!b?.bookingAmount)continue;const due=dateOnly(b.nextPaymentDate);if(!due||!today)continue;const days=Math.round((today.getTime()-due.getTime())/86400000);let bucket='UPCOMING',action='Monitor',level='NORMAL';if(days===-7||days===-3) {bucket=`D-${Math.abs(days)}`;action='Payment reminder due';}else if(days===0){bucket='DUE TODAY';action='Collect payment today';level='HIGH'}else if(days>0&&days<=3){bucket='OVERDUE 1-3D';action='Collections follow-up';level='HIGH'}else if(days>=7){bucket='ESCALATE 7D+';action='Manager escalation + call';level='CRITICAL'}else if(days>0){bucket='OVERDUE';action='Collections follow-up';level='HIGH'}else continue;queue.push({leadId,name:m.buyerName||leadId,amount:b.bookingAmount,dueDate:b.nextPaymentDate,daysOverdue:Math.max(days,0),bucket,action,level,assignedSalesperson:m.assignedSalesperson||'',updatedAt:new Date().toISOString()})}
queue.sort((a,b)=>({CRITICAL:0,HIGH:1,NORMAL:2}[a.level]-({CRITICAL:0,HIGH:1,NORMAL:2}[b.level])||b.daysOverdue-a.daysOverdue));return res.status(200).setHeader('Cache-Control','no-store').json({today:today?.toISOString().slice(0,10),queue,count:queue.length,critical:queue.filter(x=>x.level==='CRITICAL').length})}catch(e){console.error(e);return res.status(500).json({error:'Unable to build payment escalation queue.'})}}