import { createHmac } from 'node:crypto';
import { get, head, put } from '@vercel/blob';

const PATH = 'crm/referrals.json';
function header(req:any,name:string){const h=req?.headers;if(h&&typeof h.get==='function')return h.get(name)||'';return h?.[name.toLowerCase()]||h?.[name]||'';}
function sessionToken(){const p=process.env.DASHBOARD_PASSWORD||'';return p?createHmac('sha256',p).update('anjanay-heights-crm-session').digest('hex'):'';}
function cookie(req:any,name:string){const raw=String(header(req,'cookie')||'');const x=raw.split(';').map((v:string)=>v.trim()).find((v:string)=>v.startsWith(`${name}=`));return x?decodeURIComponent(x.slice(name.length+1)):'';}
function auth(req:any){const p=process.env.DASHBOARD_PASSWORD||'';return Boolean((p&&header(req,'authorization')===`Bearer ${p}`)||(sessionToken()&&cookie(req,'ah_crm_session')===sessionToken()));}
function send(res:any,status:number,body:unknown){return res.status(status).setHeader('Cache-Control','no-store').json(body);}
async function readStore(){try{const info:any=await head(PATH);if(!info?.url)return {};const r:any=await get(info.url,{access:'private',useCache:false});return r?.stream?await new Response(r.stream).json():{};}catch{return {};}}
async function writeStore(data:any){await put(PATH,JSON.stringify(data),{access:'private',addRandomSuffix:false,allowOverwrite:true,contentType:'application/json'});}
function phone(v:any){const p=String(v||'').replace(/\D/g,'');return p.length===10?`91${p}`:p;}
export default async function handler(req:any,res:any){if(!auth(req))return send(res,401,{error:'Unauthorized'});if(req.method==='GET'){const store=await readStore();return send(res,200,{ok:true,requests:Array.isArray(store?.requests)?store.requests:[]});}if(req.method!=='POST')return send(res,405,{error:'Method not allowed'});const b=req.body&&typeof req.body==='object'?req.body:{};const leadId=String(b.leadId||'').trim();const name=String(b.name||'Customer').trim().slice(0,100);const recipient=phone(b.phone);if(!leadId||recipient.length<11)return send(res,400,{error:'leadId and valid phone are required'});try{const base=`${header(req,'x-forwarded-proto')||'https'}://${header(req,'host')||''}`;const p=header(req,'authorization')||`Bearer ${process.env.DASHBOARD_PASSWORD||''}`;const metaResponse=await fetch(`${base}/api/lead-meta?refresh=${Date.now()}`,{headers:{Authorization:p},cache:'no-store'});const metaPayload=await metaResponse.json();if(!metaResponse.ok)throw new Error('Unable to read CRM metadata');const meta=metaPayload?.meta?.[leadId]||{};if(meta.siteVisitStatus!=='Completed'&&String(meta.status||'').toLowerCase()!=='closed')return send(res,400,{error:'Referral request is available after a completed site visit or closed deal'});const store=await readStore();const requests=Array.isArray(store?.requests)?store.requests:[];const existing=requests.find((x:any)=>x.leadId===leadId);if(existing)return send(res,409,{error:'Referral request already prepared',requestedAt:existing.requestedAt,whatsappUrl:existing.whatsappUrl});const requestedAt=new Date().toISOString();const message=`Hi ${name}, thank you for choosing Anjanay Heights. If you know a friend, colleague or family member looking to buy, sell or invest in property in Noida/NCR, you can share our contact with them. We would be happy to help them too. Thank you for the referral.`;const item={id:`ref-${Date.now()}-${Math.random().toString(36).slice(2,8)}`,leadId,name,recipient,requestedAt,message,whatsappUrl:`https://wa.me/${recipient}?text=${encodeURIComponent(message)}`};await writeStore({requests:[...requests.slice(-499),item]});return send(res,200,{ok:true,...item});}catch(e){console.error('referral-request error',e);return send(res,500,{error:'Unable to prepare referral request'});}}
