import { get, list, put } from '@vercel/blob';
import { notifyFollowUpReminder } from './follow-up-push';
const auths=[...(process.env.VERCEL_OIDC_TOKEN&&process.env.BLOB_STORE_ID?[{oidcToken:process.env.VERCEL_OIDC_TOKEN,storeId:process.env.BLOB_STORE_ID}]:[]),...(process.env.BLOB_READ_WRITE_TOKEN?[{token:process.env.BLOB_READ_WRITE_TOKEN}]:[])];
async function blob<T>(fn:(a:any)=>Promise<T>){let last:any;for(const a of [{},...auths])try{return await fn(a)}catch(e){last=e}throw last}
async function read(url:string){const r:any=await blob(a=>get(url,{access:'private',useCache:false,...a}));return r?.stream?await new Response(r.stream).json():null}
async function load(prefix:string){const r:any=await blob(a=>list({prefix,...a}));return Promise.all((r.blobs||[]).map(async(b:any)=>{try{return await read(b.url)}catch{return null}})).then(x=>x.filter(Boolean))}
function auth(req:any){const secret=process.env.CRON_SECRET||'';if(!secret)return true;const h=req.headers?.authorization||req.headers?.get?.('authorization')||'';return h===`Bearer ${secret}`}
function visitDate(value:any){if(!value)return null;const d=new Date(String(value));return Number.isNaN(d.getTime())?null:d}
function dateOnly(value:any){const d=visitDate(value);return d?new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kolkata'}).format(d):''}
export default async function handler(req:any,res:any){if(req.method!=='GET')return res.status(405).json({error:'Method not allowed'});if(!auth(req))return res.status(401).json({error:'Unauthorized'});try{const [leads,meta]=await Promise.all([load('leads/'),load('crm/lead-meta.json').then(x=>x[0]||{})]);const now=Date.now(),changed={...meta};let t24=0,t2=0,missed=0;for(const lead of leads){const m=meta?.[lead.id]||{};const status=String(m.siteVisitStatus||'Scheduled');const when=visitDate(m.siteVisitDateTime);if(!when||['Completed','Cancelled'].includes(status))continue;const diff=(when.getTime()-now)/3600000;const next={...m};let changedItem=false;if(diff>=22&&diff<=26&&!m.siteVisitReminder24hAt){const result=await notifyFollowUpReminder({id:lead.id,name:lead.name,phone:lead.phone,priority:m.priority,nextAction:'Confirm Site Visit (T-24h)',followUp:dateOnly(when),siteVisit:true,reminderType:'T-24H'});next.siteVisitReminder24hAt=new Date().toISOString();next.siteVisitReminder24hSent=Number(result?.sent||0)>0;changedItem=true;t24++;}if(diff>=1&&diff<=3&&!m.siteVisitReminder2hAt){const result=await notifyFollowUpReminder({id:lead.id,name:lead.name,phone:lead.phone,priority:m.priority,nextAction:'Confirm Site Visit (T-2h)',followUp:dateOnly(when),siteVisit:true,reminderType:'T-2H'});next.siteVisitReminder2hAt=new Date().toISOString();next.siteVisitReminder2hSent=Number(result?.sent||0)>0;changedItem=true;t2++;}if(diff<0&&!m.siteVisitMissedAt){const result=await notifyFollowUpReminder({id:lead.id,name:lead.name,phone:lead.phone,priority:m.priority,nextAction:'Site Visit Missed — Contact Customer',followUp:dateOnly(when),siteVisit:true,reminderType:'MISSED'});next.siteVisitMissedAt=new Date().toISOString();next.siteVisitMissedSent=Number(result?.sent||0)>0;changedItem=true;missed++;}if(changedItem)changed[lead.id]=next;}if(t24||t2||missed)await blob(a=>put('crm/lead-meta.json',JSON.stringify(changed),{access:'private',addRandomSuffix:false,allowOverwrite:true,contentType:'application/json',...a}));return res.status(200).json({ok:true,t24,t2,missed,checked:leads.length,generatedAt:new Date().toISOString()})}catch(e){console.error('site-visit-reminders error',e);return res.status(500).json({error:'Unable to process site visit reminders'})}}