import { useEffect, useMemo, useState } from 'react';

type Lead = { id: string; created_at: string; name: string; phone: string; form_name: string; lead_type: string; source?: string; utm_source?: string; utm_medium?: string; utm_campaign?: string; priority?: string; qualification?: string; };
type Meta = { status?: string; nextAction?: string; priority?: string; siteVisitStatus?: string; };
const CRM_SESSION_KEY = 'anjanay-heights-crm-password';
const SALES_STAGES = ['New', 'Contacted', 'Interested', 'Site Visit', 'Negotiation', 'Deal', 'Booking', 'Payment', 'Closed'];
function sourceOf(lead: Lead) { const raw = String(lead.source || lead.utm_source || lead.utm_medium || `${lead.form_name || ''} ${lead.lead_type || ''}`).toLowerCase(); if (raw.includes('whatsapp') || raw === 'wa') return 'WhatsApp'; if (raw.includes('facebook') || raw.includes('instagram') || raw.includes('meta')) return 'Meta'; if (raw.includes('google')) return 'Google'; if (raw.includes('referral') || raw.includes('refer')) return 'Referral'; if (raw.includes('99acres')) return '99acres'; if (raw.includes('magicbricks')) return 'MagicBricks'; return 'Website'; }
export default function CampaignPerformance() {
 const [password,setPassword]=useState(''); const [leads,setLeads]=useState<Lead[]>([]); const [meta,setMeta]=useState<Record<string,Meta>>({}); const [loggedIn,setLoggedIn]=useState(false); const [loading,setLoading]=useState(false); const [error,setError]=useState('');
 const [monthlyTarget,setMonthlyTarget]=useState(500000); const [avgCommission,setAvgCommission]=useState(170000);
 const requestedSource=typeof window!=='undefined'?new URLSearchParams(window.location.search).get('source'):null; const sourceFilter=requestedSource==='meta'?'Meta':requestedSource==='google'?'Google':null;
 async function load(token=password){const auth=token.trim();if(!auth)return;setLoading(true);setError('');try{const headers={Authorization:`Bearer ${auth}`,'Cache-Control':'no-cache'};const [leadResponse,metaResponse]=await Promise.all([fetch('/api/leads',{headers,cache:'no-store'}),fetch('/api/lead-meta',{headers,cache:'no-store'})]);const data=await leadResponse.json().catch(()=>({}));const metaData=await metaResponse.json().catch(()=>({}));if(!leadResponse.ok)throw new Error(data.error||'Unable to load leads');setLeads(data.leads||[]);setMeta(metaData.meta||{});setPassword(auth);setLoggedIn(true);sessionStorage.setItem(CRM_SESSION_KEY,auth)}catch(e){setLoggedIn(false);setError(e instanceof Error?e.message:'Unable to load CRM data')}finally{setLoading(false)}}
 useEffect(()=>{const stored=sessionStorage.getItem(CRM_SESSION_KEY)||'';if(stored)void load(stored)},[]);
 const visibleLeads=useMemo(()=>sourceFilter?leads.filter(l=>sourceOf(l)===sourceFilter):leads,[leads,sourceFilter]);
 const campaigns=useMemo(()=>{const map=new Map<string,{campaign:string;source:string;medium:string;count:number;latest:string}>();for(const lead of visibleLeads){const campaign=String(lead.utm_campaign||'').trim()||'Unattributed';const source=sourceOf(lead);const medium=String(lead.utm_medium||'').trim()||'—';const key=`${campaign}|${source}|${medium}`;const existing=map.get(key);if(existing){existing.count+=1;if(lead.created_at>existing.latest)existing.latest=lead.created_at}else map.set(key,{campaign,source,medium,count:1,latest:lead.created_at})}return [...map.values()].sort((a,b)=>b.count-a.count||b.latest.localeCompare(a.latest))},[visibleLeads]);
 const qualified=visibleLeads.filter(l=>String(l.qualification||'').toLowerCase()==='qualified'||['hot','very hot'].includes(String(l.priority||'').toLowerCase())).length;
 const stageCounts=useMemo(()=>Object.fromEntries(SALES_STAGES.map(stage=>[stage,visibleLeads.filter(l=>String(meta[l.id]?.status||'New')===stage).length])),[visibleLeads,meta]);
 const progressed=visibleLeads.filter(l=>String(meta[l.id]?.status||'New')!=='New').length;
 const targetPlan=useMemo(()=>{const target=Math.max(0,Number(monthlyTarget)||0);const commission=Math.max(1,Number(avgCommission)||1);const deals=Math.ceil(target/commission);const siteVisits=Math.max(deals*3,Math.ceil(deals/0.25));const qualifiedLeads=Math.max(siteVisits*2,Math.ceil(siteVisits/0.5));const enquiries=Math.max(qualifiedLeads*3,Math.ceil(qualifiedLeads/0.35));return {target,commission,deals,siteVisits,qualifiedLeads,enquiries}},[monthlyTarget,avgCommission]);
 if(!loggedIn)return <div className="min-h-screen bg-slate-50 flex items-center justify-center px-4"><form onSubmit={e=>{e.preventDefault();void load()}} className="w-full max-w-md bg-white rounded-2xl shadow-xl p-8"><h1 className="text-3xl font-bold text-[#1A365D] text-center">Campaign Performance</h1><p className="text-gray-500 text-center mt-2">See campaigns and the sales journey from enquiry to deal.</p><input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="CRM password" className="w-full border rounded-xl px-4 py-3 mt-8"/>{error&&<p className="text-red-600 text-sm mt-3">{error}</p>}<button disabled={loading} className="w-full mt-5 bg-[#1A365D] text-white rounded-xl py-3 font-semibold">{loading?'Loading...':'Open Performance'}</button></form></div>;
 return <div className="min-h-screen bg-slate-50 p-4 sm:p-8"><div className="mx-auto max-w-6xl"><div className="flex flex-wrap items-center justify-between gap-3 mb-6"><div><p className="text-sm font-semibold uppercase tracking-wider text-slate-500">Anjanay Heights CRM</p><h1 className="text-3xl font-bold text-[#1A365D] mt-1">📣 {sourceFilter?`${sourceFilter} Ads Performance`:'Campaign Performance'}</h1><p className="text-slate-600 mt-1">{sourceFilter?`Track ${sourceFilter} enquiries and their sales progress.`:'Measure enquiries, qualification and sales conversion.'}</p></div><div className="flex gap-2"><a href="/admin" className="rounded-lg border bg-white px-4 py-2 text-sm font-semibold">Dashboard</a>{sourceFilter&&<a href="/admin/campaign-performance" className="rounded-lg border bg-white px-4 py-2 text-sm font-semibold">All Sources</a>}<button onClick={()=>void load()} className="rounded-lg bg-[#1A365D] text-white px-4 py-2 text-sm font-semibold">Refresh</button></div></div>
 <div className="grid sm:grid-cols-4 gap-4 mb-6"><div className="bg-white rounded-2xl p-5 shadow-sm"><p className="text-slate-500 text-sm">{sourceFilter||'Total'} enquiries</p><p className="text-3xl font-bold text-[#1A365D] mt-1">{visibleLeads.length}</p></div><div className="bg-white rounded-2xl p-5 shadow-sm"><p className="text-slate-500 text-sm">Qualified / Hot</p><p className="text-3xl font-bold text-[#1A365D] mt-1">{qualified}</p></div><div className="bg-white rounded-2xl p-5 shadow-sm"><p className="text-slate-500 text-sm">In sales journey</p><p className="text-3xl font-bold text-[#1A365D] mt-1">{progressed}</p></div><div className="bg-white rounded-2xl p-5 shadow-sm"><p className="text-slate-500 text-sm">Deal / Booking / Closed</p><p className="text-3xl font-bold text-[#1A365D] mt-1">{stageCounts.Deal+stageCounts.Booking+stageCounts.Closed}</p></div></div>
 <section className="bg-white rounded-2xl p-5 shadow-sm mb-6 border border-slate-200"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-wider text-slate-500">Private CRM target planner</p><h2 className="text-2xl font-bold text-[#1A365D] mt-1">🎯 ₹5 Lakh Monthly Sales Target</h2><p className="text-sm text-slate-500 mt-1">Planning targets only — actual commission and conversion depend on closed deals.</p></div><div className="grid grid-cols-2 gap-2"><label className="text-xs text-slate-500">Monthly target ₹<input type="number" min="0" step="10000" value={monthlyTarget} onChange={e=>setMonthlyTarget(Number(e.target.value)||0)} className="block w-36 border rounded-lg px-3 py-2 mt-1 text-sm font-semibold"/></label><label className="text-xs text-slate-500">Avg. commission ₹<input type="number" min="1" step="10000" value={avgCommission} onChange={e=>setAvgCommission(Number(e.target.value)||1)} className="block w-36 border rounded-lg px-3 py-2 mt-1 text-sm font-semibold"/></label></div></div><div className="grid grid-cols-2 sm:grid-cols-5 gap-3 mt-5"><div className="rounded-xl bg-slate-50 p-4"><p className="text-xs text-slate-500">Target</p><p className="text-xl font-bold text-[#1A365D]">₹{targetPlan.target.toLocaleString('en-IN')}</p></div><div className="rounded-xl bg-slate-50 p-4"><p className="text-xs text-slate-500">Deals needed</p><p className="text-xl font-bold">{targetPlan.deals}</p></div><div className="rounded-xl bg-slate-50 p-4"><p className="text-xs text-slate-500">Site visits target</p><p className="text-xl font-bold">{targetPlan.siteVisits}</p></div><div className="rounded-xl bg-slate-50 p-4"><p className="text-xs text-slate-500">Qualified leads target</p><p className="text-xl font-bold">{targetPlan.qualifiedLeads}</p></div><div className="rounded-xl bg-slate-50 p-4"><p className="text-xs text-slate-500">Enquiries target</p><p className="text-xl font-bold">{targetPlan.enquiries}</p></div></div><div className="mt-4 grid sm:grid-cols-3 gap-3 text-sm"><div className="rounded-xl border p-3"><b>Current deals</b><span className="float-right">{stageCounts.Deal+stageCounts.Booking+stageCounts.Closed}</span></div><div className="rounded-xl border p-3"><b>Deals remaining</b><span className="float-right">{Math.max(0,targetPlan.deals-(stageCounts.Deal+stageCounts.Booking+stageCounts.Closed))}</span></div><div className="rounded-xl border p-3"><b>Target progress</b><span className="float-right">{targetPlan.deals?Math.min(100,Math.round((stageCounts.Deal+stageCounts.Booking+stageCounts.Closed)/targetPlan.deals*100)):0}%</span></div></div></section>
 <div className="bg-white rounded-2xl p-5 shadow-sm mb-6"><div className="flex items-center justify-between gap-3 mb-4"><div><h2 className="font-bold text-slate-900 text-lg">Sales Conversion Funnel</h2><p className="text-sm text-slate-500">Lead → Call → Site Visit → Negotiation → Deal → Booking</p></div><span className="text-xs font-semibold rounded-full bg-slate-100 px-3 py-1">Live CRM data</span></div><div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-5 gap-3">{SALES_STAGES.map((stage,index)=>{const count=stageCounts[stage]||0;const rate=visibleLeads.length?Math.round(count/visibleLeads.length*100):0;return <div key={stage} className="rounded-xl border border-slate-200 p-4"><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">{index+1}. {stage}</p><p className="text-2xl font-bold text-[#1A365D] mt-2">{count}</p><p className="text-xs text-slate-500 mt-1">{rate}% of enquiries</p></div>})}</div></div>
 <div className="overflow-x-auto rounded-2xl border border-slate-200 bg-white shadow-sm"><table className="w-full min-w-[700px] text-left text-sm"><thead className="bg-slate-50 text-slate-500"><tr><th className="px-5 py-4">Campaign</th><th className="px-5 py-4">Source</th><th className="px-5 py-4">Medium</th><th className="px-5 py-4">Enquiries</th><th className="px-5 py-4">Latest</th></tr></thead><tbody>{campaigns.map(c=><tr key={`${c.campaign}-${c.source}-${c.medium}`} className="border-t"><td className="px-5 py-4 font-semibold text-slate-900">{c.campaign}</td><td className="px-5 py-4">{c.source}</td><td className="px-5 py-4">{c.medium}</td><td className="px-5 py-4 font-bold text-[#1A365D]">{c.count}</td><td className="px-5 py-4 text-slate-500">{new Date(c.latest).toLocaleString('en-IN')}</td></tr>)}{campaigns.length===0&&<tr><td colSpan={5} className="px-5 py-10 text-center text-slate-500">No enquiries yet.</td></tr>}</tbody></table></div><div className="mt-6 rounded-2xl bg-white p-5 shadow-sm"><h2 className="font-bold text-slate-900">Sales decision</h2><p className="text-sm text-slate-600 mt-1">Now track where leads are getting stuck and focus sales effort on moving qualified buyers from call to site visit, negotiation and booking.</p></div></div></div>;
}
