import { useState } from 'react';
import { MessageCircle, Sparkles, X, CheckCircle2 } from 'lucide-react';

const WA='https://wa.me/919289771222';
const starter=['2 BHK in Noida under my budget','Best investment option','I want a site visit'];

export default function CustomerAiAdvisor(){
 const [open,setOpen]=useState(false),[q,setQ]=useState(''),[answer,setAnswer]=useState(''),[propertyIds,setPropertyIds]=useState<string[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState('');
 const [capture,setCapture]=useState(false),[name,setName]=useState(''),[phone,setPhone]=useState(''),[email,setEmail]=useState(''),[capturing,setCapturing]=useState(false),[captured,setCaptured]=useState(false);
 async function ask(value=q){const question=value.trim();if(!question||loading)return;setQ(question);setLoading(true);setError('');setAnswer('');setPropertyIds([]);setCaptured(false);try{const r=await fetch('/api/customer-ai',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question})});const x=await r.json();if(!r.ok)throw new Error(x.error||'Unable to answer');setAnswer(x.text||'');setPropertyIds(Array.isArray(x.propertyIds)?x.propertyIds:[]);setCapture(true);}catch(e){setError(e instanceof Error?e.message:'Please try again.')}finally{setLoading(false)}}
 async function captureLead(){if(!name.trim()||phone.replace(/\D/g,'').length<10){setError('Name and a valid 10-digit phone number are required.');return}setCapturing(true);setError('');try{const r=await fetch('/api/leads',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:name.trim(),phone:phone.trim(),email:email.trim(),source:'website-ai',form_name:'ai-property-advisor',requirement:q,message:answer,property_name:propertyIds.length?`AI matched properties: ${propertyIds.join(', ')}`:'',next_step:/site visit|visit/i.test(q)?'Site Visit':'Property Options',timeline:/today|urgent|asap|immediate|this week/i.test(q)?'Immediate':'',lead_type:/sell|seller|selling/i.test(q)?'SELL':/invest|investment|roi/i.test(q)?'INVEST':'BUY'})});const x=await r.json();if(!r.ok)throw new Error(x.error||'Unable to save lead');setCaptured(true);setCapture(false);}catch(e){setError(e instanceof Error?e.message:'Unable to save your request.')}finally{setCapturing(false)}}
 return <>
  <button onClick={()=>setOpen(true)} aria-label="Ask AI Property Advisor" className="fixed bottom-24 right-5 z-50 flex items-center gap-2 rounded-full bg-[#1A365D] text-white px-4 py-3 shadow-2xl hover:scale-105 transition-transform"><Sparkles size={18}/><span className="text-sm font-bold">AI Property Advisor</span></button>
  {open&&<div className="fixed inset-0 z-[60] bg-black/30 p-4 flex items-end md:items-center justify-center" onClick={()=>setOpen(false)}>
   <div onClick={e=>e.stopPropagation()} className="w-full max-w-md rounded-3xl bg-white shadow-2xl overflow-hidden">
    <div className="bg-[#1A365D] text-white p-5 flex justify-between items-start"><div><p className="text-xs uppercase tracking-widest text-[#C2A36B] font-bold">ANJANAY HEIGHTS</p><h2 className="text-xl font-bold mt-1">AI Property Advisor</h2><p className="text-xs text-white/70 mt-1">Answers from live available inventory only</p></div><button onClick={()=>setOpen(false)}><X/></button></div>
    <div className="p-4 space-y-3"><div className="flex flex-wrap gap-2">{starter.map(s=><button key={s} onClick={()=>void ask(s)} className="text-xs border rounded-full px-3 py-2 text-[#1A365D] hover:bg-slate-50">{s}</button>)}</div>
    {answer&&<div className="rounded-2xl bg-slate-50 p-4 text-sm text-slate-700 whitespace-pre-wrap leading-relaxed">{answer}</div>}{captured&&<div className="rounded-2xl bg-green-50 text-green-800 p-4 text-sm flex gap-2 items-start"><CheckCircle2 size={18} className="mt-0.5 shrink-0"/><div><b>Requirement received.</b><div className="mt-1">Our sales team can now follow up with your matched property options and site visit.</div></div></div>}{error&&<div className="rounded-xl bg-red-50 text-red-700 p-3 text-sm">{error}</div>}
    {capture&&!captured&&<div className="rounded-2xl border border-slate-200 p-4 space-y-2"><p className="text-sm font-bold text-[#1A365D]">Get these property options from our sales team</p><input value={name} onChange={e=>setName(e.target.value)} placeholder="Your name" className="w-full border rounded-xl p-3 text-sm"/><input value={phone} onChange={e=>setPhone(e.target.value)} inputMode="tel" placeholder="10-digit mobile number" className="w-full border rounded-xl p-3 text-sm"/><input value={email} onChange={e=>setEmail(e.target.value)} type="email" placeholder="Email (optional)" className="w-full border rounded-xl p-3 text-sm"/><button disabled={capturing} onClick={()=>void captureLead()} className="w-full rounded-xl bg-[#1A365D] text-white py-3 font-bold disabled:opacity-50">{capturing?'Sending to Sales…':'Send Requirement to Sales'}</button><p className="text-[10px] text-gray-400">Your requirement is added to the ANJANAY HEIGHTS sales CRM. Existing phone numbers are deduplicated.</p></div>}
    <textarea value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();void ask()}}} rows={3} placeholder="Tell me location, BHK, budget or investment goal…" className="w-full border rounded-2xl p-3 text-sm outline-none focus:ring-2 focus:ring-slate-200"/>
    <div className="grid grid-cols-2 gap-2"><button disabled={loading} onClick={()=>void ask()} className="rounded-xl bg-[#1A365D] text-white py-3 font-bold disabled:opacity-50">{loading?'Thinking…':'Ask Advisor'}</button><a href={WA} target="_blank" rel="noreferrer" className="rounded-xl border py-3 font-bold text-center text-[#1A365D]"><MessageCircle size={16} className="inline mr-1"/>WhatsApp Sales</a></div>
    <p className="text-[11px] text-gray-400">AI does not confirm availability, pricing or legal facts beyond the live inventory. Consultant confirmation is required.</p></div>
   </div></div>}
 </>
}
