import { useEffect, useState } from 'react';
export default function PaymentScheduleCenter(){
 const [items,setItems]=useState<any[]>([]); const [leadId,setLeadId]=useState(''); const [dealValue,setDealValue]=useState(''); const [bookingDate,setBookingDate]=useState(new Date().toISOString().slice(0,10)); const [msg,setMsg]=useState('');
 const headers=()=>{const p=sessionStorage.getItem('anjanay-heights-crm-password')||sessionStorage.getItem('crm_password')||'';return p?{Authorization:`Bearer ${p}`}:{} as Record<string,string>};
 const load=async()=>{const r=await fetch('/api/payment-schedule',{headers:headers()});const j=await r.json();setItems(Array.isArray(j.schedules)?j.schedules:[])};
 useEffect(()=>{load()},[]);
 const save=async()=>{setMsg('');const r=await fetch('/api/payment-schedule',{method:'POST',headers:{...headers(),'Content-Type':'application/json'},body:JSON.stringify({leadId,dealValue:Number(dealValue),bookingDate})});const j=await r.json();setMsg(r.ok?'Schedule created':'Unable to create schedule');if(r.ok){setItems(x=>[...x.filter(v=>v.leadId!==leadId),j.schedule])}};
 const money=(n:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(n||0);
 return <div className="min-h-screen bg-slate-950 text-white p-6"><div className="max-w-6xl mx-auto"><p className="text-emerald-400 text-xs tracking-widest">ANJANAY HEIGHTS • COLLECTION ENGINE</p><h1 className="text-3xl font-bold mt-2">Payment Milestone Planner</h1><p className="text-slate-400 mt-1">Booking → Agreement → Construction → Final Demand → Possession</p><div className="bg-white text-slate-900 rounded-2xl p-5 mt-6"><div className="grid md:grid-cols-4 gap-3"><input className="border rounded-xl p-3" placeholder="Lead ID" value={leadId} onChange={e=>setLeadId(e.target.value)}/><input className="border rounded-xl p-3" type="number" placeholder="Deal value ₹" value={dealValue} onChange={e=>setDealValue(e.target.value)}/><input className="border rounded-xl p-3" type="date" value={bookingDate} onChange={e=>setBookingDate(e.target.value)}/><button onClick={save} className="rounded-xl bg-slate-950 text-white font-semibold">Generate Milestones</button></div>{msg&&<p className="mt-3 text-sm">{msg}</p>}</div><div className="space-y-4 mt-6">{items.map(s=><div key={s.leadId} className="bg-white text-slate-900 rounded-2xl p-5"><div className="font-bold">Lead: {s.leadId} • Total {money(s.totalAmount)}</div><div className="grid md:grid-cols-5 gap-3 mt-4">{s.milestones?.map((m:any)=><div key={m.id} className="border rounded-xl p-3"><b>{m.name}</b><div>{money(m.amount)}</div><small>{m.percentage}% • {m.dueDate}</small><div className="text-xs font-semibold mt-2">{m.state}</div></div>)}</div><p className="text-xs text-slate-500 mt-4">Planning template only; confirm builder-specific demand dates and amounts against the applicable agreement.</p></div>)}</div></div></div>
}