import { useEffect, useState } from 'react';

type Item={id:string;name?:string;phone?:string;intent?:string;priority?:string;action?:string;reason?:string;score?:number;followUp?:string};

export default function PriorityActionPanel(){
 const [items,setItems]=useState<Item[]>([]); const [loading,setLoading]=useState(true);
 useEffect(()=>{let live=true;(async()=>{try{const password=sessionStorage.getItem('anjanay-heights-crm-password')||sessionStorage.getItem('crm_password')||'';const r=await fetch('/api/sales-priority-queue',{headers:password?{Authorization:`Bearer ${password}`}:{},cache:'no-store'});const d=await r.json();if(live&&r.ok)setItems((d.queue||[]).slice(0,5).map((x:any)=>({id:x.id,name:x.name,phone:x.phone,intent:x.intent,priority:x.priority,action:x.action||x.nextAction,reason:x.routeReason||x.reason,score:x.score,followUp:x.followUp})));}finally{if(live)setLoading(false)}})();return()=>{live=false}},[]);
 if(loading||!items.length)return null;
 return <section className="bg-white border rounded-2xl p-4 mb-5"><div className="flex items-center justify-between gap-3 mb-3"><div><p className="text-xs uppercase tracking-widest text-[#C2A36B] font-bold">AI sales priority</p><h2 className="text-lg font-bold text-[#1A365D]">Next 5 actions</h2></div><span className="text-xs font-semibold text-gray-500">Live queue</span></div><div className="grid lg:grid-cols-5 gap-3">{items.map((x)=><div key={x.id} className="rounded-xl border bg-[#F8FAFC] p-3"><div className="flex justify-between gap-2"><b className="text-sm text-[#1A365D] truncate">{x.name||'Lead'}</b><span className="text-[10px] font-bold">{x.intent||'BUY'}</span></div><p className="text-xs font-bold mt-2">{x.action||'CALL LEAD'}</p><p className="text-[11px] text-gray-500 mt-1 line-clamp-2">{x.reason||'Priority routing'}</p><div className="flex gap-2 mt-3">{x.phone&&<a className="text-xs font-bold text-[#1A365D]" href={`tel:${x.phone}`}>Call</a>}{x.phone&&<a className="text-xs font-bold text-emerald-700" target="_blank" rel="noreferrer" href={`https://wa.me/${x.phone.replace(/\\D/g,'')}`}>WhatsApp</a>}</div></div>)}</div></section>;
}
