import { useEffect, useMemo, useState } from 'react';
type Lead={id:string;name?:string;phone?:string;location?:string;property_type?:string};
type Meta={siteVisitStatus?:string;siteVisitDateTime?:string;status?:string};
type Referral={leadId:string;requestedAt:string;whatsappUrl?:string};
const auth=()=>sessionStorage.getItem('anjanay-heights-crm-password')||sessionStorage.getItem('crm_password')||'';
export default function ReferralQueue(){const[leads,setLeads]=useState<Lead[]>([]),[meta,setMeta]=useState<Record<string,Meta>>({}),[sent,setSent]=useState<Record<string,Referral>>({}),[loading,setLoading]=useState(true),[busy,setBusy]=useState(''),[error,setError]=useState('');
async function load(){const p=auth();if(!p){setError('Open CRM and sign in first.');setLoading(false);return;}setLoading(true);try{const h={Authorization:`Bearer ${p}`};const[a,b,c]=await Promise.all([fetch('/api/leads?refresh='+Date.now(),{headers:h,cache:'no-store'}),fetch('/api/lead-meta?refresh='+Date.now(),{headers:h,cache:'no-store'}),fetch('/api/referral-request?refresh='+Date.now(),{headers:h,cache:'no-store'})]);const l=await a.json(),m=await b.json(),r=await c.json();if(!a.ok)throw new Error(l.error||'Unable to load leads');setLeads(l.leads||[]);setMeta(m.meta||{});setSent(Object.fromEntries((r.requests||[]).map((x:any)=>[x.leadId,x])));}catch(e){setError(e instanceof Error?e.message:'Unable to load referral queue');}finally{setLoading(false);}}
useEffect(()=>{void load()},[]);
const queue=useMemo(()=>leads.filter(l=>{const m=meta[l.id]||{};return m.siteVisitStatus==='Completed'||String(m.status||'').toLowerCase()==='closed';}).sort((a,b)=>new Date(meta[b.id]?.siteVisitDateTime||0).getTime()-new Date(meta[a.id]?.siteVisitDateTime||0).getTime()),[leads,meta]);
async function prepare(l:Lead){const p=auth();if(!p||!l.phone)return;setBusy(l.id);setError('');try{const r=await fetch('/api/referral-request',{method:'POST',headers:{Authorization:`Bearer ${p}`,'Content-Type':'application/json'},body:JSON.stringify({leadId:l.id,name:l.name,phone:l.phone})});const x=await r.json();if(!r.ok)throw new Error(x.error||'Unable to prepare referral');setSent(v=>({...v,[l.id]:x}));window.open(x.whatsappUrl,'_blank','noopener,noreferrer');}catch(e){setError(e instanceof Error?e.message:'Unable to prepare referral');}finally{setBusy('');}}
return <div className="min-h-screen bg-[#F5F7FA] p-4 md:p-6"><div className="max-w-6xl mx-auto"><div className="flex flex-wrap justify-between items-center gap-3 mb-5"><div><a href="/admin" className="text-sm font-semibold text-[#1A365D]">← CRM Dashboard</a><p className="text-xs font-bold uppercase tracking-widest text-[#C2A36B] mt-3">Anjanay Heights</p><h1 className="text-3xl font-bold text-[#1A365D]">Referral & Repeat Business</h1><p className="text-gray-500">Happy site-visit / closed customers → new warm introductions.</p></div><button onClick={()=>void load()} className="bg-[#1A365D] text-white rounded-xl px-4 py-2.5 font-semibold">↻ Refresh</button></div>{error&&<div className="mb-4 bg-red-50 text-red-700 rounded-xl p-3">{error}</div>}<div className="grid grid-cols-2 md:grid-cols-3 gap-3 mb-5"><div className="bg-white border rounded-2xl p-4"><p className="text-xs text-gray-500">Eligible customers</p><b className="text-2xl text-[#1A365D]">{queue.length}</b></div><div className="bg-white border rounded-2xl p-4"><p className="text-xs text-gray-500">Referral asks prepared</p><b className="text-2xl text-[#1A365D]">{Object.keys(sent).length}</b></div><div className="bg-white border rounded-2xl p-4"><p className="text-xs text-gray-500">Approach</p><b className="text-sm text-[#1A365D]">Warm introduction, no incentive</b></div></div>{loading?<div className="bg-white border rounded-2xl p-10 text-center text-gray-500">Loading eligible customers…</div>:<div className="space-y-3">{queue.map(l=>{const done=sent[l.id];return <article key={l.id} className="bg-white border rounded-2xl p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-bold text-lg text-[#1A365D]">{l.name||'Customer'}</h2><p className="text-sm text-gray-500">{l.phone||'No phone'} · {l.property_type||'Property'} · {l.location||'NCR'}</p>{done&&<p className="text-xs font-semibold text-emerald-700 mt-1">✓ Referral message prepared {new Date(done.requestedAt).toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'})}</p>}</div><button disabled={Boolean(done)||busy===l.id} onClick={()=>void prepare(l)} className="bg-emerald-600 disabled:opacity-50 text-white rounded-xl px-4 py-2.5 font-semibold">{busy===l.id?'Preparing…':done?'✓ Prepared':'🤝 Ask for Referral'}</button></div><p className="text-xs text-gray-500 mt-3">Ask only for an optional genuine introduction to someone who may need property help. No ratings or incentives.</p></article>})}{!queue.length&&<div className="bg-white border rounded-2xl p-10 text-center text-gray-500">No completed visits or closed customers found.</div>}</div>}</div></div>}
