import { useEffect, useMemo, useState } from 'react';

type Lead={id:string;name?:string;phone?:string;property_type?:string;location?:string;budget?:string;created_at?:string};
type Meta={status?:string;priority?:string;dealValue?:string;conversionProbability?:string;siteVisitDateTime?:string;salesStage?:string;assignedSalesperson?:string};
const money=(v?:string)=>{if(!v)return 0;const n=Number(String(v).replace(/[^0-9.]/g,''));return Number.isFinite(n)?n:0};
const pct=(v?:string)=>{const n=Number(String(v||'').replace(/[^0-9.]/g,''));return Number.isFinite(n)?Math.max(0,Math.min(100,n)):0};
const rank=(p?:string)=>p==='Very Hot'?4:p==='Hot'?3:p==='Warm'?2:1;
export default function RevenuePriorityPanel(){
 const [password]=useState(()=>sessionStorage.getItem('anjanay-heights-crm-password')||sessionStorage.getItem('crm_password')||'');
 const [leads,setLeads]=useState<Lead[]>([]); const [meta,setMeta]=useState<Record<string,Meta>>({}); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
 const load=async()=>{if(!password){setLoading(false);return;}try{setError('');const h={Authorization:`Bearer ${password}`};const [a,b]=await Promise.all([fetch('/api/leads?revenue='+Date.now(),{headers:h,cache:'no-store'}),fetch('/api/lead-meta?revenue='+Date.now(),{headers:h,cache:'no-store'})]);const l=await a.json(),m=await b.json();if(!a.ok)throw new Error(l.error||'Unable to load leads');setLeads(l.leads||[]);setMeta(m.meta||{});}catch(e){setError(e instanceof Error?e.message:'Unable to load revenue queue')}finally{setLoading(false)}};
 useEffect(()=>{void load();const t=window.setInterval(()=>void load(),60000);return()=>window.clearInterval(t)},[password]);
 const rows=useMemo(()=>leads.map(lead=>{const m=meta[lead.id]||{};const value=money(m.dealValue||lead.budget);const probability=pct(m.conversionProbability);const intentBoost=rank(m.priority)*8;const stageBoost=/NEGOTIATION/i.test(m.salesStage||m.status||'')?20:/SITE VISIT/i.test(m.salesStage||m.status||'')?15:/BOOKING/i.test(m.salesStage||m.status||'')?25:0;const revenueScore=Math.round(Math.min(100,(value>0?Math.log10(value+1)*14:0)+probability*.55+intentBoost+stageBoost));return {lead,m,value,probability,revenueScore}}).filter(x=>x.m.status!=='Closed'&&x.m.status!=='Lost').sort((a,b)=>b.revenueScore-a.revenueScore).slice(0,6),[leads,meta]);
 const weighted=rows.reduce((s,x)=>s+x.value*x.probability/100,0);
 if(!password)return null;
 return <section className="bg-white border rounded-2xl p-4 mb-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs uppercase tracking-widest text-[#C2A36B] font-bold">Revenue intelligence</p><h2 className="text-xl font-bold text-[#1A365D]">Money-first priority</h2><p className="text-sm text-gray-500">Lead score ke saath expected deal value ko weight karke sales team ko highest-value actions dikhata hai.</p></div><div className="rounded-xl bg-[#F8FAFC] px-4 py-3"><span className="text-xs text-gray-400 block">VISIBLE EXPECTED VALUE</span><b className="text-lg text-[#1A365D]">₹{Math.round(weighted).toLocaleString('en-IN')}</b></div></div>{error&&<p className="text-sm text-red-600 mt-3">{error}</p>}{loading?<p className="text-sm text-gray-500 mt-4">Calculating revenue priority…</p>:rows.length===0?<p className="text-sm text-gray-500 mt-4">No active revenue opportunities.</p>:<div className="grid lg:grid-cols-2 gap-3 mt-4">{rows.map(x=><div key={x.lead.id} className="border rounded-xl p-3 bg-[#FFFCF5]"><div className="flex justify-between gap-3"><div><b className="text-[#1A365D]">{x.lead.name||'Lead'}</b><p className="text-xs text-gray-500">{x.lead.location||'NCR'} · {x.m.assignedSalesperson||'Unassigned'}</p></div><span className="text-xs font-bold bg-[#F4F7FB] text-[#1A365D] rounded-full px-2 py-1">{x.revenueScore}/100</span></div><div className="grid grid-cols-3 gap-2 mt-3 text-xs"><div><span className="text-gray-400 block">DEAL VALUE</span><b>₹{Math.round(x.value).toLocaleString('en-IN')}</b></div><div><span className="text-gray-400 block">CLOSING</span><b>{x.probability}%</b></div><div><span className="text-gray-400 block">STAGE</span><b>{x.m.salesStage||x.m.status||'NEW'}</b></div></div><div className="flex gap-2 mt-3"><a href={`/admin/sales-journey?lead=${encodeURIComponent(x.lead.id)}`} className="border rounded-lg px-3 py-2 text-sm font-semibold">Open Journey</a>{x.lead.phone&&<a href={`tel:${x.lead.phone}`} className="bg-[#1A365D] text-white rounded-lg px-3 py-2 text-sm font-semibold">Call</a>}</div></div>)}</div>}</section>;
}