import { useEffect, useMemo, useState } from 'react';

type Lead={id:string;name?:string;phone?:string;location?:string;property_type?:string};
type Meta={siteVisitStatus?:string;siteVisitDateTime?:string;reviewRequestedAt?:string};
const GOOGLE_REVIEW_URL='https://www.google.com/search?q=Anjanay+Heights+Noida';
const auth=()=>sessionStorage.getItem('anjanay-heights-crm-password')||sessionStorage.getItem('crm_password')||'';
const wa=(phone?:string,message='')=>{const d=String(phone||'').replace(/\D/g,'');if(!d)return '';const n=d.length===10?`91${d}`:d;return `https://wa.me/${n}?text=${encodeURIComponent(message)}`};
export default function ReviewRequestQueue(){
 const [leads,setLeads]=useState<Lead[]>([]),[meta,setMeta]=useState<Record<string,Meta>>({}),[loading,setLoading]=useState(true),[error,setError]=useState('');
 async function load(){const p=auth();if(!p){setError('Open CRM and sign in first.');setLoading(false);return}setLoading(true);try{const h={Authorization:`Bearer ${p}`};const [a,b]=await Promise.all([fetch('/api/leads?refresh='+Date.now(),{headers:h,cache:'no-store'}),fetch('/api/lead-meta?refresh='+Date.now(),{headers:h,cache:'no-store'})]);const l=await a.json(),m=await b.json();if(!a.ok)throw new Error(l.error||'Unable to load leads');setLeads(l.leads||[]);setMeta(m.meta||{});}catch(e){setError(e instanceof Error?e.message:'Unable to load review queue')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 const queue=useMemo(()=>leads.filter(l=>meta[l.id]?.siteVisitStatus==='Completed').sort((a,b)=>new Date(meta[b.id]?.siteVisitDateTime||0).getTime()-new Date(meta[a.id]?.siteVisitDateTime||0).getTime()),[leads,meta]);
 const message=(l:Lead)=>`Hi ${l.name||'there'}, thank you for visiting with Anjanay Heights. If our team helped you, please share your genuine experience on Google: ${GOOGLE_REVIEW_URL} Honest feedback helps future property buyers.`;
 return <div className="min-h-screen bg-[#F5F7FA] p-4 md:p-6"><div className="max-w-6xl mx-auto"><div className="flex flex-wrap justify-between items-center gap-3 mb-5"><div><p className="text-xs font-bold uppercase tracking-widest text-[#C2A36B]">Anjanay Heights</p><h1 className="text-3xl font-bold text-[#1A365D]">Review Request Queue</h1><p className="text-gray-500">Completed site visits → genuine review request</p></div><button onClick={()=>void load()} className="bg-[#1A365D] text-white rounded-xl px-4 py-2.5 font-semibold">↻ Refresh</button></div>{error&&<div className="mb-4 bg-red-50 text-red-700 rounded-xl px-4 py-3 text-sm">{error}</div>}<div className="grid grid-cols-2 gap-3 mb-5"><div className="bg-white border rounded-2xl p-4"><p className="text-xs text-gray-500">Completed visits</p><p className="text-2xl font-bold text-[#1A365D] mt-1">{queue.length}</p></div><div className="bg-white border rounded-2xl p-4"><p className="text-xs text-gray-500">Action</p><p className="text-sm font-bold text-[#1A365D] mt-2">Ask only genuine customers</p></div></div>{loading?<div className="text-center py-12 text-gray-500">Loading…</div>:<div className="space-y-3">{queue.map(l=>{const m=meta[l.id]||{};return <article key={l.id} className="bg-white border rounded-2xl p-4"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="font-bold text-lg text-[#1A365D]">{l.name||'Unnamed'}</h2><p className="text-sm text-gray-500">{l.phone||'No phone'} · {l.property_type||'Property'} · {l.location||'Location'}</p><p className="text-xs text-gray-400 mt-1">Site visit completed {m.siteVisitDateTime?new Date(m.siteVisitDateTime).toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'}):''}</p></div><div className="flex gap-2"><a href={wa(l.phone,message(l))} target="_blank" rel="noreferrer" className="bg-[#1A365D] text-white rounded-xl px-4 py-2.5 font-semibold">💬 Ask for Review</a><a href={GOOGLE_REVIEW_URL} target="_blank" rel="noreferrer" className="border rounded-xl px-4 py-2.5 font-semibold">Open Google</a></div></div><p className="text-xs text-gray-500 mt-3">Request genuine feedback only. Never offer incentives or ask for a specific rating.</p></article>})}{!queue.length&&<div className="bg-white border rounded-2xl p-10 text-center text-gray-500">No completed site visits are ready for a review request.</div>}</div>}</div></div>;
}
