import { useEffect, useState } from 'react';

type Row={id:string;name?:string;phone?:string;intent?:string;location?:string;propertyType?:string;budget?:string;priority?:string;status?:string;salesStage?:string;action?:string;reason?:string;followUp?:string};
const KEY='anjanay-heights-crm-password';
const wa=(phone?:string,text='')=>phone?`https://wa.me/${phone.replace(/\D/g,'')}?text=${encodeURIComponent(text)}`:'#';
export default function SalesPriorityQueue(){
 const [rows,setRows]=useState<Row[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');
 useEffect(()=>{const p=sessionStorage.getItem(KEY)||sessionStorage.getItem('crm_password')||'';if(!p){setLoading(false);setError('Open CRM and sign in first.');return;}fetch('/api/sales-priority-queue?refresh='+Date.now(),{headers:{Authorization:`Bearer ${p}`},cache:'no-store'}).then(async r=>{const j=await r.json();if(!r.ok)throw new Error(j.error||'Unable to load queue');setRows(j.queue||[])}).catch(e=>setError(e instanceof Error?e.message:'Unable to load queue')).finally(()=>setLoading(false))},[]);
 return <div className="min-h-screen bg-[#F5F7FA] p-4 md:p-7"><div className="max-w-6xl mx-auto"><a href="/admin/sales-cockpit" className="text-sm font-semibold text-[#1A365D]">← Sales Cockpit</a><div className="flex flex-wrap items-end justify-between gap-3 mt-4 mb-6"><div><p className="text-xs uppercase tracking-widest text-[#C2A36B] font-bold">Anjanay Heights</p><h1 className="text-3xl font-bold text-[#1A365D]">⚡ Priority Call Queue</h1><p className="text-gray-500">Sabse pehle jis lead par action lena hai.</p></div><div className="bg-white border rounded-xl px-4 py-2 font-bold text-[#1A365D]">{rows.length} active leads</div></div>{error&&<div className="bg-red-50 text-red-700 rounded-xl p-3 mb-4">{error}</div>}{loading?<div className="bg-white border rounded-2xl p-10 text-center text-gray-500">Building priority queue…</div>:<div className="space-y-3">{rows.map((r,n)=><div key={r.id} className="bg-white border rounded-2xl p-4 md:p-5"><div className="flex flex-col md:flex-row md:items-center gap-4"><div className="w-9 h-9 rounded-full bg-[#1A365D] text-white flex items-center justify-center font-bold">{n+1}</div><div className="flex-1"><div className="flex flex-wrap gap-2"><span className="text-xs font-bold px-2 py-1 rounded-full bg-red-50 text-red-700">{r.priority||'Warm'}</span><span className="text-xs font-bold px-2 py-1 rounded-full bg-[#F4F7FB] text-[#1A365D]">{r.intent}</span><span className="text-xs font-semibold px-2 py-1 rounded-full bg-gray-100">{r.status||'New'}</span></div><h2 className="text-lg font-bold text-[#1A365D] mt-2">{r.name||'Unnamed lead'}</h2><p className="text-sm text-gray-500">{r.phone||'No phone'} · {r.propertyType||'Property'} · {r.location||'NCR'} · {r.budget||'Budget not captured'}</p><p className="text-sm font-semibold mt-2">{r.action} <span className="font-normal text-gray-500">— {r.reason}</span></p></div><div className="flex flex-wrap gap-2"><a href={`tel:${r.phone||''}`} className="bg-[#1A365D] text-white rounded-xl px-4 py-2.5 font-semibold">📞 Call</a><a target="_blank" rel="noreferrer" href={wa(r.phone,`Hello ${r.name||''}, Anjanay Heights here. We have options matching your ${r.propertyType||'property'} requirement in ${r.location||'NCR'}. Can we discuss the best options?`)} className="bg-emerald-600 text-white rounded-xl px-4 py-2.5 font-semibold">💬 WhatsApp</a><a href={`/admin/lead-360?lead=${encodeURIComponent(r.id)}`} className="border rounded-xl px-4 py-2.5 font-semibold">Lead 360 →</a></div></div></div>)}{!rows.length&&<div className="bg-white border rounded-2xl p-10 text-center text-gray-500">No active leads.</div>}</div>}</div></div>;
}
