import { get, list } from '@vercel/blob';

type Property={id:string;title:string;propertyType:string;location:string;price:string;minBudget:number|null;maxBudget:number|null;area:string;bedrooms:string;status:'Available'|'Hold'|'Sold'|'Inactive';description:string;createdAt:string;photos?:string[];videoUrl?:string};
const ITEM_PREFIX='crm/properties/item-';
const blobAuthCandidates:Record<string,string>[]=[{},...(process.env.VERCEL_OIDC_TOKEN&&process.env.BLOB_STORE_ID?[{oidcToken:process.env.VERCEL_OIDC_TOKEN,storeId:process.env.BLOB_STORE_ID}]:[]),...(process.env.BLOB_READ_WRITE_TOKEN?[{token:process.env.BLOB_READ_WRITE_TOKEN}]:[])];
function blobAuthError(e:unknown){const x=e as any;return /BlobAccessError|access denied|valid token|credentials|unauthorized|forbidden/i.test(`${x?.name||x?.constructor?.name||''} ${x?.message||''}`)}
async function withBlobAuth<T>(op:(auth:Record<string,string>)=>Promise<T>):Promise<T>{let last:any=new Error('No Vercel Blob credentials configured.');for(const auth of blobAuthCandidates){try{return await op(auth)}catch(e){last=e;if(!blobAuthError(e))throw e}}throw last}
function send(res:any,status:number,body:unknown){return res.status(status).setHeader('Cache-Control','no-store').setHeader('Pragma','no-cache').json(body)}
async function readItems(){const blobs:any[]=[];let cursor:string|undefined;do{const p=await withBlobAuth(a=>list({prefix:ITEM_PREFIX,cursor,...a}));blobs.push(...(p.blobs||[]));cursor=p.hasMore?p.cursor:undefined}while(cursor);const out:Property[]=[];for(const b of blobs){try{const r=await withBlobAuth(a=>get(b.url||b.pathname,{access:'private',...a}));if(r?.stream){const v=JSON.parse(await new Response(r.stream).text());if(v?.id)out.push(v)}}catch(e){if(!blobAuthError(e))throw e}}return out}
function matchesBhk(p:Property,bhk:string){if(!bhk)return true;const q=bhk.toLowerCase().replace(/\s/g,'');const b=String(p.bedrooms||'').toLowerCase().replace(/\s/g,'');return b.includes(q)||b.includes(q.replace('bhk',''))}
function budgetOverlap(p:Property,budget:number|null){if(!budget)return true;const min=p.minBudget??null,max=p.maxBudget??null;if(min==null&&max==null)return true;return (min==null||min<=budget)&&(max==null||max>=budget||min<=budget)}
export default async function handler(req:any,res:any){if(req.method!=='GET')return send(res,405,{error:'Method not allowed'});try{const all=await readItems();const available=all.filter(p=>p.status==='Available');const url=new URL(req.url||'http://localhost');const q=(url.searchParams.get('q')||'').trim().toLowerCase();const bhk=(url.searchParams.get('bhk')||'').trim();const location=(url.searchParams.get('location')||'').trim().toLowerCase();const type=(url.searchParams.get('type')||'').trim().toLowerCase();const budget=Number(url.searchParams.get('budget')||0)||null;const properties=available.filter(p=>{const hay=`${p.title} ${p.propertyType} ${p.location} ${p.price} ${p.area} ${p.bedrooms} ${p.description}`.toLowerCase();return (!q||hay.includes(q))&&(!location||p.location.toLowerCase().includes(location))&&(!type||p.propertyType.toLowerCase().includes(type))&&matchesBhk(p,bhk)&&budgetOverlap(p,budget)}).sort((a,b)=>new Date(b.createdAt).getTime()-new Date(a.createdAt).getTime()).map(p=>({id:p.id,title:p.title,propertyType:p.propertyType,location:p.location,price:p.price,minBudget:p.minBudget,maxBudget:p.maxBudget,area:p.area,bedrooms:p.bedrooms,status:p.status,description:p.description,photos:p.photos||[],videoUrl:p.videoUrl||'',createdAt:p.createdAt,marketOpportunity:/third-party|market opportunity|researched/i.test(p.description)}));return send(res,200,{properties,availableCount:available.length,totalCount:all.length,updatedAt:new Date().toISOString()})}catch(e:any){return send(res,500,{error:e?.message||'Unable to load live inventory.'})}}
