import { get, head, list, put } from '@vercel/blob';
import { createHash, createHmac } from 'node:crypto';
import { notifyNewLead } from './push.js';
import { assignLead } from './lead-assignment.js';
import { sendAssignedLeadAlert } from './assigned-lead-alert.js';

const blobAuthCandidates = [
  ...(process.env.VERCEL_OIDC_TOKEN && process.env.BLOB_STORE_ID ? [{ oidcToken: process.env.VERCEL_OIDC_TOKEN, storeId: process.env.BLOB_STORE_ID }] : []),
  ...(process.env.BLOB_READ_WRITE_TOKEN ? [{ token: process.env.BLOB_READ_WRITE_TOKEN }] : []),
];
function send(res: any, status: number, body: unknown) { return res.status(status).setHeader('Cache-Control', 'no-store').json(body); }
function header(req: any, name: string) { const h = req?.headers; if (h && typeof h.get === 'function') return h.get(name) || ''; return h?.[name.toLowerCase()] || h?.[name] || ''; }
function sessionToken() { const password = process.env.DASHBOARD_PASSWORD || ''; return password ? createHmac('sha256', password).update('anjanay-heights-crm-session').digest('hex').toString() : ''; }
function cookie(req: any, name: string) { const raw = String(header(req, 'cookie') || ''); const match = raw.split(';').map((v: string) => v.trim()).find((v: string) => v.startsWith(`${name}=`)); return match ? decodeURIComponent(match.slice(name.length + 1)) : ''; }
function setSessionCookie(res: any) { const token = sessionToken(); if (token) res.setHeader('Set-Cookie', `ah_crm_session=${encodeURIComponent(token)}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=28800`); }
function authorized(req: any) { const password = process.env.DASHBOARD_PASSWORD || ''; return Boolean(password && header(req, 'authorization') === `Bearer ${password}`) || Boolean(sessionToken() && cookie(req, 'ah_crm_session') === sessionToken()); }
function body(req: any) { if (req?.body && typeof req.body === 'object' && !Buffer.isBuffer(req.body)) return req.body; const raw = Buffer.isBuffer(req?.body) ? req.body.toString() : String(req?.body || ''); if (!raw) return {}; if (String(header(req, 'content-type')).includes('application/json')) { try { return JSON.parse(raw) || {}; } catch { return {}; } } return Object.fromEntries(new URLSearchParams(raw).entries()); }
function phone(v: string) { const d = String(v || '').replace(/\D/g, ''); return d.length === 10 ? `91${d}` : d; }
function key(v: string) { return `leads/phone-${createHash('sha256').update(phone(v)).digest('hex')}.json`; }
function scoreLead(lead: any) { let score = 0; const text = [lead.property_type, lead.location, lead.budget, lead.timeline, lead.requirement, lead.message, lead.property_name, lead.next_step].join(' ').toLowerCase(); if (lead.phone) score += 10; if (lead.email) score += 5; if (/site visit|visit|immediate|urgent|today|asap|this week|within 7 days|within 1 week/.test(text)) score += 25; if (/shortlist|price discussion|serious purchase|ready to buy|ready|cash|loan approved|approval/.test(text)) score += 20; if (lead.budget) score += 15; if (lead.location) score += 10; if (lead.property_type) score += 10; if (/buy|purchase|booking|invest|investment/.test(text)) score += 5; if (/sell|selling|seller/.test(text)) score += 5; return Math.min(100, score); }
function priority(score: number) { return score >= 75 ? 'Very Hot' : score >= 55 ? 'Hot' : score >= 30 ? 'Warm' : 'Cold'; }
function qualification(score: number) { return score >= 55 ? 'Qualified' : 'New'; }
function salesStage(score: number, lead: any) { const text = [lead.timeline, lead.requirement, lead.message, lead.next_step].join(' ').toLowerCase(); if (/booking|book now|token|advance/.test(text)) return 'NEGOTIATION'; if (/site visit|visit/.test(text)) return 'SITE VISIT SCHEDULED'; if (score >= 55) return 'QUALIFIED'; return 'NEW LEAD'; }
function recommendedAction(score: number, lead: any) { const text = [lead.timeline, lead.requirement, lead.message, lead.next_step].join(' ').toLowerCase(); if (/booking|book now|token|advance/.test(text)) return 'Call immediately — booking/negotiation intent'; if (/site visit|visit/.test(text)) return 'Call now — confirm site visit'; if (score >= 75) return 'Call within 15 minutes'; if (score >= 55) return 'Call today and send matched properties'; if (score >= 30) return 'Qualify budget, location and timeline'; return 'Start first contact and capture requirement'; }
function istDate(offsetDays = 0) { const parts = new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Kolkata', year: 'numeric', month: '2-digit', day: '2-digit' }).formatToParts(new Date()); const y = Number(parts.find(p => p.type === 'year')?.value); const m = Number(parts.find(p => p.type === 'month')?.value) - 1; const d = Number(parts.find(p => p.type === 'day')?.value); return new Date(Date.UTC(y, m, d + offsetDays)).toISOString().slice(0, 10); }
function initialFollowUp(lead: any, score: number) { const urgent = /site visit|visit|immediate|urgent|today|asap|this week|within 7 days|within 1 week/i.test([lead.timeline, lead.requirement, lead.message, lead.next_step].join(' ')); const days = urgent || score >= 75 ? 0 : 1; return `${istDate(days)}T${days === 0 ? '16:00' : '10:00'}`; }
function isBlobAuthError(error: unknown) { const value = error as any; return /BlobAccessError|access denied|valid token|credentials|unauthorized|forbidden/i.test(`${String(value?.name ?? value?.constructor?.name ?? '')} ${String(value?.message ?? '')}`); }
function isBlobAlreadyExistsError(error: unknown) { const value = error as any; return /already exists|allowOverwrite|BlobError/i.test(`${String(value?.name ?? value?.constructor?.name ?? '')} ${String(value?.message ?? '')}`); }
async function withBlobAuth<T>(operation: (auth: Record<string, string>) => Promise<T>) { let lastError: unknown = new Error('No Vercel Blob credentials configured.'); const attempts = [{}, ...blobAuthCandidates] as Record<string, string>[]; for (const auth of attempts) { try { return await operation(auth); } catch (error) { lastError = error; if (!isBlobAuthError(error)) throw error; } } throw lastError; }
async function read(url: string) { const r = await withBlobAuth((auth) => get(url, { access: 'private', ...auth })); return r?.statusCode === 200 && r.stream ? await new Response(r.stream).json() : null; }
async function initializeMeta(lead: any, score: number) { const path = 'crm/lead-meta.json'; try { const info: any = await withBlobAuth((auth) => head(path, auth)); if (!info?.url) return; const current = await read(info.url); if (!current || typeof current !== 'object' || current[lead.id]) return; const now = new Date().toISOString(); const status = qualification(score); const priorityValue = priority(score); const followUp = initialFollowUp(lead, score); current[lead.id] = { status, priority: priorityValue, salesStage: salesStage(score, lead), nextAction: 'Call', recommendedAction: recommendedAction(score, lead), followUp, note: 'Automatically initialized from sales-machine intake.', propertyType: lead.property_type || '', propertyName: lead.property_name || '', location: lead.location || '', budget: lead.budget || '', timeline: lead.timeline || '', nextStep: lead.next_step || '', callHistory: [], history: [{ id: `auto-${lead.id}`, at: now, action: 'Sales Machine', note: `New lead scored ${score}/100 · ${priorityValue} · ${status} · ${salesStage(score, lead)} · ${recommendedAction(score, lead)} · follow-up ${followUp}.` }] }; await withBlobAuth((auth) => put(path, JSON.stringify(current), { access: 'private', addRandomSuffix: false, allowOverwrite: true, contentType: 'application/json', ...auth })); } catch (error) { console.error('lead automation initialization error', error); } }
async function triggerCustomerWhatsApp(req: any, lead: any) { const password = process.env.DASHBOARD_PASSWORD || ''; const host = String(req?.headers?.host || ''); if (!password || !host || !lead?.phone || !process.env.WHATSAPP_ACCESS_TOKEN || !process.env.WHATSAPP_PHONE_NUMBER_ID) return { triggered: false, reason: 'Customer WhatsApp automation is not configured.' }; try { const r = await fetch(`https://${host}/api/customer-whatsapp`, { method: 'POST', headers: { authorization: `Bearer ${password}`, 'content-type': 'application/json' }, body: JSON.stringify({ name: lead.name, phone: lead.phone, location: lead.location, property_type: lead.property_type, budget: lead.budget, timeline: lead.timeline, property_name: lead.property_name, bhk: lead.bhk || '' }) }); const data = await r.json().catch(() => ({})); return { triggered: r.ok, ...(data || {}), status: r.status }; } catch (error) { console.error('customer WhatsApp trigger error', error); return { triggered: false, reason: 'Customer WhatsApp request failed.' }; } }
export default async function handler(req: any, res: any) {
  if (req.method === 'GET') { if (!authorized(req)) return send(res, 401, { error: 'Unauthorized' }); if (req?.query?._login === '1' || req?.query?._session === '1') { setSessionCookie(res); return send(res, 200, { ok: true }); } try { const r = await withBlobAuth((auth) => list({ prefix: 'leads/', ...auth })); const leads = (await Promise.all(r.blobs.map(async b => { try { return await read(b.url); } catch { return null; } }))).filter(Boolean); return send(res, 200, { leads }); } catch (e) { console.error('leads GET error', e); return send(res, 500, { error: 'Unable to load leads.' }); } }
  if (req.method === 'POST') { try { const b = body(req); if (String(b['bot-field'] || '').trim()) return send(res, 200, { ok: true }); const name = String(b.name || '').trim(); const rawPhone = String(b.phone || '').trim(); if (!name || !rawPhone) return send(res, 400, { error: 'Name and phone are required.' }); const q = req?.query || {}; const lead = { id: crypto.randomUUID(), created_at: new Date().toISOString(), name, phone: rawPhone, email: String(b.email || '').trim(), form_name: String(b['form-name'] || 'property-lead'), lead_type: String(b.lead_type || ''), source: String(b.source || b.lead_source || 'Website'), utm_source: String(b.utm_source || q.utm_source || '').trim(), utm_medium: String(b.utm_medium || q.utm_medium || '').trim(), utm_campaign: String(b.utm_campaign || q.utm_campaign || '').trim(), property_name: String(b.property_name || '').trim(), property_type: String(b.property_type || '').trim(), location: String(b.location || '').trim(), budget: String(b.budget || '').trim(), timeline: String(b.timeline || '').trim(), next_step: String(b.next_step || '').trim(), requirement: String(b.requirement || '').trim(), message: String(b.message || '').trim(), bhk: String(b.bhk || '').trim() }; let savedLead = lead; try { await withBlobAuth((auth) => put(key(rawPhone), JSON.stringify(lead), { access: 'private', addRandomSuffix: false, contentType: 'application/json', allowOverwrite: false, ...auth })); } catch (error) { if (!isBlobAlreadyExistsError(error)) throw error; const existing = await withBlobAuth((auth) => head(key(rawPhone), auth)); if (!existing?.url) throw error; const existingLead = await read(existing.url); if (existingLead && typeof existingLead === 'object') savedLead = existingLead; }
      const score = scoreLead(savedLead); const leadPriority = priority(score); const qualificationStatus = qualification(score); const stage = salesStage(score, savedLead); const action = recommendedAction(score, savedLead); const followUp = initialFollowUp(savedLead, score); await initializeMeta(savedLead, score); let assignment:any={assignedSalesperson:'',assignedPhone:'',reason:'Assignment unavailable'}; try { assignment=await assignLead(savedLead); } catch(error){ console.error('lead assignment delivery error',error); }
      let assignmentAlert:any={sent:false,reason:'Assignment alert not attempted'}; try { assignmentAlert=await sendAssignedLeadAlert(savedLead,assignment); } catch(error){ console.error('assigned salesperson WhatsApp alert error',error); assignmentAlert={sent:false,reason:'Assignment alert failed'}; }
      try { await notifyNewLead({...savedLead, assignedSalesperson:assignment.assignedSalesperson, assignmentReason:assignment.reason}, leadPriority); } catch (error) { console.error('lead push delivery error', error); }
      let customerWhatsApp:any={triggered:false,reason:'Customer WhatsApp automation skipped.'}; try { customerWhatsApp=await triggerCustomerWhatsApp(req,savedLead); } catch(error){ console.error('customer WhatsApp automation error',error); }
      const waPhone = phone(savedLead.phone || ''); const whatsappUrl = waPhone ? `https://wa.me/${waPhone}` : ''; return send(res, 200, { ok: true, lead: savedLead, followUp, priority: leadPriority, qualification: qualificationStatus, score, salesStage: stage, recommendedAction: action, nextAction: 'Call', assignedSalesperson: assignment.assignedSalesperson, assignedPhone: assignment.assignedPhone, assignmentReason: assignment.reason, assignmentAlert: assignmentAlert.whatsapp || assignmentAlert, customerWhatsApp, whatsappUrl, duplicate: savedLead.id !== lead.id });
    } catch (e) { console.error('leads POST error', e); return send(res, 500, { error: 'Unable to save your request.' }); } }
  return send(res, 405, { error: 'Method not allowed' });
}
