import { get, head, list, put } from '@vercel/blob';
const auths=[...(process.env.VERCEL_OIDC_TOKEN&&process.env.BLOB_STORE_ID?[{oidcToken:process.env.VERCEL_OIDC_TOKEN,storeId:process.env.BLOB_STORE_ID}]:[]),...(process.env.BLOB_READ_WRITE_TOKEN?[{token:process.env.BLOB_READ_WRITE_TOKEN}]:[])];
const send=(res:any,status:number,body:unknown)=>res.status(status).setHeader('Cache-Control','no-store').json(body);
const header=(req:any,n:string)=>req?.headers?.get?n&&req.headers.get(n)||'':req?.headers?.[n.toLowerCase()]||'';
const authorized=(req:any)=>Boolean(process.env.DASHBOARD_PASSWORD&&header(req,'authorization')===`Bearer ${process.env.DASHBOARD_PASSWORD}`);
async function blob<T>(fn:(a:any)=>Promise<T>){let last:any;for(const a of [{},...auths])try{return await fn(a)}catch(e){last=e}throw last}
async function read(url:string){const r:any=await blob(a=>get(url,{access:'private',...a}));return r?.stream?await new Response(r.stream).json():null}
async function collection(path:string){try{const h:any=await blob(a=>head(path,a));return h?.url?await read(h.url):{}}catch{return {}}}
export function leadIntent(l:any){const t=[l.lead_type,l.requirement,l.message,l.property_type].join(' ').toLowerCase();if(/sell|seller|selling|resale/.test(t))return'SELL';if(/invest|roi|return/.test(t))return'INVEST';return'BUY'}
function matchAgent(l:any,agents:any[]){const i=leadIntent(l),loc=String(l.location||'').toLowerCase(),type=String(l.property_type||'').toLowerCase();const eligible=agents.filter(a=>a.active!==false).filter(a=>!a.intent||String(a.intent).toUpperCase()===i||String(a.intent).toUpperCase()==='ALL').filter(a=>!a.locations||a.locations.some((x:string)=>loc.includes(String(x).toLowerCase()))).filter(a=>!a.propertyTypes||a.propertyTypes.some((x:string)=>type.includes(String(x).toLowerCase())));const pool=eligible.length?eligible:agents.filter(a=>a.active!==false);if(!pool.length)return null;return[...pool].sort((a,b)=>Number(a.assignmentCount||0)-Number(b.assignmentCount||0))[0]||null}
async function saveAssignment(metaPath:string,meta:any,agent:any,l:any){const now=new Date().toISOString();meta[l.id]={...(meta[l.id]||{}),assignedSalesperson:agent.name||'',assignedPhone:agent.phone||'',assignmentIntent:leadIntent(l),assignmentReason:'Auto-routed by intent/location/property type + least-assigned load',assignedAt:now,history:[...((meta[l.id]||{}).history||[]),{id:`assignment-${l.id}-${Date.now()}`,at:now,action:'Lead Assignment',note:`Assigned to ${agent.name||'salesperson'} · ${leadIntent(l)} · ${l.location||'location not specified'}.`}]};await blob(a=>put(metaPath,JSON.stringify(meta),{access:'private',addRandomSuffix:false,allowOverwrite:true,contentType:'application/json',...a}))}
async function incrementAgentLoad(raw:any,agent:any){const agents=Array.isArray(raw)?raw:Array.isArray(raw?.agents)?raw.agents:[];const updated=agents.map((a:any)=>a===agent||String(a.name||'')===String(agent.name||'')?{...a,assignmentCount:Number(a.assignmentCount||0)+1,lastAssignedAt:new Date().toISOString()}:a);const payload=Array.isArray(raw)?updated:{...raw,agents:updated};await blob(a=>put('crm/sales-agents.json',JSON.stringify(payload),{access:'private',addRandomSuffix:false,allowOverwrite:true,contentType:'application/json',...a}));return updated}
export async function assignLead(l:any){const metaPath='crm/lead-meta.json',meta=await collection(metaPath),existing=meta[l.id]||{};if(existing.assignedSalesperson||existing.assignedAgent)return{assignedSalesperson:existing.assignedSalesperson||existing.assignedAgent,assignedPhone:existing.assignedPhone||'',reason:'Existing assignment preserved'};const raw=await collection('crm/sales-agents.json'),agents=Array.isArray(raw)?raw:Array.isArray(raw?.agents)?raw.agents:[],agent=matchAgent(l,agents);if(!agent)return{assignedSalesperson:'',assignedPhone:'',reason:'No active salesperson configured'};await saveAssignment(metaPath,meta,agent,l);try{await incrementAgentLoad(raw,agent)}catch(error){console.error('sales agent load update error',error)}return{assignedSalesperson:agent.name||'',assignedPhone:agent.phone||'',reason:'Auto-routed by intent/location/property type + least-assigned load'}}
export default async function handler(req:any,res:any){if(req.method!=='GET')return send(res,405,{error:'Method not allowed'});if(!authorized(req))return send(res,401,{error:'Unauthorized'});try{const r:any=await blob(a=>list({prefix:'leads/',...a})),leads=(await Promise.all(r.blobs.map(async(b:any)=>{try{return await read(b.url)}catch{return null}}))).filter(Boolean),meta=await collection('crm/lead-meta.json'),raw=await collection('crm/sales-agents.json'),agents=Array.isArray(raw)?raw:Array.isArray(raw?.agents)?raw.agents:[],assignments=leads.map((l:any)=>{const m=meta[l.id]||{},existing=m.assignedSalesperson||m.assignedAgent,a=existing?null:matchAgent(l,agents);return{leadId:l.id,name:l.name,intent:leadIntent(l),assignedSalesperson:existing||a?.name||null,assignedPhone:m.assignedPhone||a?.phone||null,reason:existing?'Existing assignment preserved':a?'Auto-routed by intent/location/property type + least-assigned load':'No active salesperson configured'}});return send(res,200,{ok:true,generatedAt:new Date().toISOString(),configuredAgents:agents.length,assignments})}catch(e){console.error('lead assignment error',e);return send(res,500,{error:'Unable to build assignment queue.'})}}
