import { get, head, list, put } from '@vercel/blob';

const auths = [
  ...(process.env.VERCEL_OIDC_TOKEN && process.env.BLOB_STORE_ID ? [{ oidcToken: process.env.VERCEL_OIDC_TOKEN, storeId: process.env.BLOB_STORE_ID }] : []),
  ...(process.env.BLOB_READ_WRITE_TOKEN ? [{ token: process.env.BLOB_READ_WRITE_TOKEN }] : []),
];
const send=(res:any,status:number,body:unknown)=>res.status(status).setHeader('Cache-Control','no-store').json(body);
const header=(req:any,n:string)=>req?.headers?.get?n&&req.headers.get(n)||'':req?.headers?.[n.toLowerCase()]||'';
const authorized=(req:any)=>Boolean(process.env.DASHBOARD_PASSWORD&&header(req,'authorization')===`Bearer ${process.env.DASHBOARD_PASSWORD}`);
async function blob<T>(fn:(a:any)=>Promise<T>){let last:any;for(const a of [{},...auths])try{return await fn(a)}catch(e){last=e}throw last}
async function read(url:string){const r:any=await blob(a=>get(url,{access:'private',...a}));return r?.stream?await new Response(r.stream).json():null}
async function collection(path:string){try{const h:any=await blob(a=>head(path,a));return h?.url?await read(h.url):{}}catch{return {}}}
function intent(l:any){const t=[l.lead_type,l.requirement,l.message,l.property_type].join(' ').toLowerCase();if(/sell|seller|selling|resale/.test(t))return'SELL';if(/invest|roi|return/.test(t))return'INVEST';return'BUY'}
function matchAgent(l:any,agents:any[],used:Set<string>){const i=intent(l);const loc=String(l.location||'').toLowerCase();const type=String(l.property_type||'').toLowerCase();const eligible=agents.filter(a=>a.active!==false).filter(a=>!a.intent||String(a.intent).toUpperCase()===i||a.intent==='ALL').filter(a=>!a.locations||a.locations.some((x:string)=>loc.includes(String(x).toLowerCase()))).filter(a=>!a.propertyTypes||a.propertyTypes.some((x:string)=>type.includes(String(x).toLowerCase())));const pool=eligible.length?eligible:agents.filter(a=>a.active!==false);if(!pool.length)return null;return [...pool].sort((a,b)=>Number(a.assignmentCount||0)-Number(b.assignmentCount||0))[0]||null}
export default async function handler(req:any,res:any){if(req.method!=='GET')return send(res,405,{error:'Method not allowed'});if(!authorized(req))return send(res,401,{error:'Unauthorized'});try{const leadsResult:any=await blob(a=>list({prefix:'leads/',...a}));const leads=(await Promise.all(leadsResult.blobs.map(async(b:any)=>{try{return await read(b.url)}catch{return null}}))).filter(Boolean);const meta=await collection('crm/lead-meta.json');const agentsRaw=await collection('crm/sales-agents.json');const agents=Array.isArray(agentsRaw)?agentsRaw:Array.isArray(agentsRaw?.agents)?agentsRaw.agents:[];const assignments=leads.map((l:any)=>{const m=meta[l.id]||{};const existing=m.assignedSalesperson||m.assignedAgent;if(existing)return{leadId:l.id,assignedSalesperson:existing,reason:'Existing assignment preserved'};const a=matchAgent(l,agents,new Set());return{leadId:l.id,name:l.name,intent:intent(l),assignedSalesperson:a?.name||null,assignedPhone:a?.phone||null,reason:a?'Auto-routed by intent/location/property type + least-assigned load':'No active salesperson configured'} });return send(res,200,{ok:true,generatedAt:new Date().toISOString(),configuredAgents:agents.length,assignments})}catch(e){console.error('lead assignment error',e);return send(res,500,{error:'Unable to build assignment queue.'})}}
