import { get, head, put } from '@vercel/blob';
import { createHmac } from 'node:crypto';
const PATH='crm/payment-ledger.json';
const candidates=[...(process.env.VERCEL_OIDC_TOKEN&&process.env.BLOB_STORE_ID?[{oidcToken:process.env.VERCEL_OIDC_TOKEN,storeId:process.env.BLOB_STORE_ID}]:[]),...(process.env.BLOB_READ_WRITE_TOKEN?[{token:process.env.BLOB_READ_WRITE_TOKEN}]:[])];
function h(req:any,n:string){const x=req?.headers;if(x&&typeof x.get==='function')return x.get(n)||'';return x?.[n.toLowerCase()]||x?.[n]||''} function ok(req:any){const p=process.env.DASHBOARD_PASSWORD||'';const t=p?createHmac('sha256',p).update('anjanay-heights-crm-session').digest('hex'):'';return Boolean((p&&h(req,'authorization')===`Bearer ${p}`)||(t&&String(h(req,'cookie')).includes(`ah_crm_session=${t}`)))}
function ae(e:any){return /access denied|credentials|unauthorized|forbidden|valid token/i.test(`${e?.name||''} ${e?.message||''}`)} async function blob<T>(fn:(a:any)=>Promise<T>){let last:any;for(const a of [{},...candidates])try{return await fn(a)}catch(e){last=e;if(!ae(e))throw e}throw last}
async function read(){try{const i:any=await blob(a=>head(PATH,a));const r:any=await blob(a=>get(i.url,{access:'private',useCache:false,...a}));return {data:await new Response(r.stream).json(),etag:i.etag}}catch(e:any){if(e?.status===404||/not found|BlobNotFound/i.test(`${e?.name||''} ${e?.message||''}`))return {data:{},etag:undefined};throw e}}
async function write(data:any,etag?:string){return blob(a=>put(PATH,JSON.stringify(data),{access:'private',addRandomSuffix:false,allowOverwrite:true,contentType:'application/json',...(etag?{ifMatch:etag}:{}),...a}))}
const clean=(v:any,n=500)=>String(v??'').slice(0,n);
export default async function handler(req:any,res:any){if(!ok(req))return res.status(401).json({error:'Unauthorized'});try{if(req.method==='GET'){const s=await read();const id=clean(req.query?.leadId,120);const data=(s.data||{}) as Record<string,any>;return res.status(200).setHeader('Cache-Control','no-store').json({ledgers:id?(data[id]||{leadId:id,entries:[]}):data})}
if(req.method==='POST'){const b=req.body&&typeof req.body==='object'?req.body:{};const leadId=clean(b.leadId,120);if(!leadId)return res.status(400).json({error:'leadId is required'});const e=b.entry&&typeof b.entry==='object'?b.entry:{};const amount=Math.max(0,Number(e.amount||0));if(!amount)return res.status(400).json({error:'amount is required'});for(let attempt=0;attempt<3;attempt++){const s=await read();const all:Record<string,any>=s.data||{};const ledger=all[leadId]||{leadId,entries:[]};const entry={id:clean(e.id||`PAY-${Date.now()}`,100),milestoneId:clean(e.milestoneId,100),amount,paidDate:clean(e.paidDate||new Date().toISOString().slice(0,10),30),paymentMode:clean(e.paymentMode,100),receiptNo:clean(e.receiptNo,100),note:clean(e.note,1000),createdAt:new Date().toISOString()};ledger.entries=[...(Array.isArray(ledger.entries)?ledger.entries:[]).filter((x:any)=>x.id!==entry.id),entry];ledger.totalPaid=ledger.entries.reduce((a:number,x:any)=>a+Number(x.amount||0),0);all[leadId]=ledger;try{await write(all,s.etag);return res.status(200).json({ok:true,ledger})}catch(e:any){if(!/precondition|etag/i.test(String(e?.message||''))||attempt===2)throw e}}}return res.status(405).json({error:'Method not allowed'})}catch(e){console.error('payment-ledger error',e);return res.status(500).json({error:'Unable to access payment ledger.'})}}
