import { get, head, put } from '@vercel/blob';

type Meta = Record<string, any>;
const META='crm/lead-meta.json';
const auths=[...(process.env.VERCEL_OIDC_TOKEN&&process.env.BLOB_STORE_ID?[{oidcToken:process.env.VERCEL_OIDC_TOKEN,storeId:process.env.BLOB_STORE_ID}]:[]),...(process.env.BLOB_READ_WRITE_TOKEN?[{token:process.env.BLOB_READ_WRITE_TOKEN}]:[])];
const ok=(req:any)=>{const p=process.env.DASHBOARD_PASSWORD||'';return !p||req.headers?.authorization===`Bearer ${p}`};
const send=(res:any,s:number,b:any)=>res.status(s).setHeader('Cache-Control','no-store').json(b);
async function withAuth<T>(fn:(a:any)=>Promise<T>){let e:any;for(const a of [{},...auths])try{return await fn(a)}catch(x){e=x}throw e}
async function read(){const h:any=await withAuth(a=>head(META,a));const r:any=await withAuth(a=>get(h.url,{access:'private',useCache:false,...a}));return {data:await new Response(r.stream).json(),etag:h.etag}}
async function write(data:any,etag?:string){await withAuth(a=>put(META,JSON.stringify(data),{access:'private',addRandomSuffix:false,allowOverwrite:true,contentType:'application/json',...(etag?{ifMatch:etag}:{}),...a}))}
const date=(d:Date)=>d.toISOString().slice(0,10);
export default async function handler(req:any,res:any){if(req.method!=='POST')return send(res,405,{error:'Method not allowed'});if(!ok(req))return send(res,401,{error:'Unauthorized'});const leadId=String(req.body?.leadId||'').trim();const outcome=String(req.body?.outcome||'').trim();const allowed=new Set(['Interested','Negotiation','Send Property Options','Follow Later','Not Interested']);if(!leadId||!allowed.has(outcome))return send(res,400,{error:'leadId and a valid outcome are required'});try{for(let attempt=0;attempt<3;attempt++){const snap=await read();const current=snap.data?.[leadId];if(!current)return send(res,404,{error:'Lead not found'});const now=new Date();const follow=new Date(now);const status=outcome==='Negotiation'?'Negotiation':outcome==='Not Interested'?'Lost':'Interested';if(outcome==='Interested')follow.setDate(follow.getDate()+1);else if(outcome==='Negotiation')follow.setDate(follow.getDate()+1);else if(outcome==='Send Property Options')follow.setDate(follow.getDate());else if(outcome==='Follow Later')follow.setDate(follow.getDate()+3);else follow.setDate(follow.getDate());const nextAction=outcome==='Negotiation'?'Follow-up':outcome==='Send Property Options'?'Send Property Options':outcome==='Not Interested'?'No Action':'Follow-up';const oldHistory=Array.isArray(current.history)?current.history:[];const item={id:`post-visit-${Date.now()}`,at:now.toISOString(),action:`Post Visit: ${outcome}`,note:String(req.body?.note||'').slice(0,1000)};const next={...current,status,nextAction,followUp:date(follow),visitFeedback:String(req.body?.feedback??current.visitFeedback??'').slice(0,2000),visitInterest:outcome,customerOffer:String(req.body?.customerOffer??current.customerOffer??'').slice(0,2000),closingProbability:String(req.body?.closingProbability??current.closingProbability??'').slice(0,100),negotiationNotes:String(req.body?.negotiationNotes??current.negotiationNotes??'').slice(0,2000),history:[...oldHistory,item].slice(-50)};if(outcome==='Negotiation'&&req.body?.dealValue!==undefined)next.dealValue=String(req.body.dealValue).slice(0,200);snap.data[leadId]=next;try{await write(snap.data,snap.etag);return send(res,200,{ok:true,leadId,outcome,status,nextAction,followUp:next.followUp,meta:next})}catch(e:any){if(!/precondition|etag|BlobPreconditionFailed/i.test(String(e?.message||e?.name||''))||attempt===2)throw e}}}catch(e){console.error(e);return send(res,500,{error:'Unable to save post-visit outcome'})}}
