import { get, list } from '@vercel/blob';

const auths = [
  ...(process.env.VERCEL_OIDC_TOKEN && process.env.BLOB_STORE_ID ? [{ oidcToken: process.env.VERCEL_OIDC_TOKEN, storeId: process.env.BLOB_STORE_ID }] : []),
  ...(process.env.BLOB_READ_WRITE_TOKEN ? [{ token: process.env.BLOB_READ_WRITE_TOKEN }] : []),
];
function header(req:any,n:string){const h=req?.headers;if(h?.get)return h.get(n)||'';return h?.[n.toLowerCase()]||h?.[n]||'';}
function send(res:any,s:number,b:unknown){return res.status(s).setHeader('Cache-Control','no-store').json(b);}
function allowed(req:any){const p=process.env.DASHBOARD_PASSWORD||'';return !p||header(req,'authorization')===`Bearer ${p}`;}
function blobErr(e:unknown){return /BlobAccessError|access denied|valid token|credentials|unauthorized|forbidden/i.test(`${String((e as any)?.name||'')} ${String((e as any)?.message||'')}`);}
async function blob<T>(fn:(a:Record<string,string>)=>Promise<T>){let last:any;for(const a of [{},...auths] as Record<string,string>[]){try{return await fn(a)}catch(e){last=e;if(!blobErr(e))throw e;}}throw last;}
async function read(url:string){const r=await blob(a=>get(url,{access:'private',useCache:false,...a}));return r?.statusCode===200&&r.stream?await new Response(r.stream).json():null;}
async function leads(){const r=await blob(a=>list({prefix:'leads/',...a}));return (await Promise.all(r.blobs.map(x=>read(x.url).catch(()=>null)))).filter(Boolean);}
async function meta(){const r=await blob(a=>list({prefix:'crm/lead-meta.json',...a}));return r.blobs[0]?((await read(r.blobs[0].url))||{}):{};}
async function properties(){const r=await blob(a=>list({prefix:'crm/properties/',...a}));return (await Promise.all(r.blobs.map(x=>read(x.url).catch(()=>null)))).filter((p:any)=>p&&p.status==='Available');}
function n(v:any){const s=String(v??'').toLowerCase().replace(/,/g,'');let x=parseFloat(s.replace(/[^0-9.]/g,''))||0;if(/crore|cr/.test(s))x*=1e7;else if(/lakh|lac/.test(s))x*=1e5;return x;}
function rank(lead:any,p:any){let score=0;const why:string[]=[];const l=(v:any)=>String(v??'').toLowerCase();const loc=l(lead.location),pl=l(p.location);if(loc&&pl&&(pl.includes(loc)||loc.includes(pl))){score+=35;why.push('location')}else if(loc&&pl&&loc.split(/[, -]+/).some((x:string)=>x.length>3&&pl.includes(x))){score+=15;why.push('nearby');}const lt=l(lead.property_type),pt=l(p.type||p.propertyType);if(lt&&pt&&(pt.includes(lt)||lt.includes(pt))){score+=20;why.push('type');}const lb=/\d+/.exec(l(lead.bhk||lead.bedrooms))?.[0],pb=/\d+/.exec(l(p.bhk||p.bedrooms))?.[0];if(lb&&pb&&lb===pb){score+=20;why.push('BHK');}const b=n(lead.budget),price=n(p.price||p.minBudget);if(b&&price){if(price<=b){score+=20;why.push('budget')}else if(price<=b*1.1){score+=10;why.push('near budget');}}return {score,why};}
export default async function handler(req:any,res:any){if(req.method!=='GET')return send(res,405,{error:'Method not allowed'});if(!allowed(req))return send(res,401,{error:'Unauthorized'});try{const [ls,ms,ps]=await Promise.all([leads(),meta(),properties()]);const active=ls.filter((l:any)=>!['Closed','Lost'].includes(ms?.[l.id]?.status));const queue=active.map((lead:any)=>{const m=ms?.[lead.id]||{};const priority=m.priority||'Warm';const urgency=priority==='Very Hot'?4:priority==='Hot'?3:priority==='Warm'?2:1;const matches=ps.map((p:any)=>{const r=rank(lead,p);return {id:p.id,title:p.title||p.name,location:p.location,price:p.price,bedrooms:p.bedrooms||p.bhk,photos:p.photos||[],score:r.score,reasons:r.why};}).filter((x:any)=>x.score>0).sort((a:any,b:any)=>b.score-a.score).slice(0,3);return {leadId:lead.id,name:lead.name||'',phone:lead.phone||'',priority,urgency,status:m.status||'New',nextAction:m.nextAction||'Call',followUp:m.followUp||'',propertyRequirement:{type:lead.property_type||'',location:lead.location||'',budget:lead.budget||'',bhk:lead.bhk||''},topMatches:matches};}).sort((a:any,b:any)=>b.urgency-a.urgency||String(a.followUp).localeCompare(String(b.followUp))).slice(0,20);return send(res,200,{ok:true,count:queue.length,queue});}catch(e){console.error('priority-match-queue',e);return send(res,500,{error:'Unable to build priority match queue'});}}
