import { get, list } from '@vercel/blob';
const authCandidates = [...(process.env.VERCEL_OIDC_TOKEN && process.env.BLOB_STORE_ID ? [{ oidcToken: process.env.VERCEL_OIDC_TOKEN, storeId: process.env.BLOB_STORE_ID }] : []), ...(process.env.BLOB_READ_WRITE_TOKEN ? [{ token: process.env.BLOB_READ_WRITE_TOKEN }] : [])];
function send(res:any,status:number,body:unknown){return res.status(status).setHeader('Cache-Control','no-store').json(body)}
async function withAuth<T>(fn:(auth:Record<string,string>)=>Promise<T>){let last:unknown=new Error('Inventory storage is not configured.');for(const auth of [{},...authCandidates] as Record<string,string>[]){try{return await fn(auth)}catch(e){last=e}}throw last}
async function read(url:string){const r:any=await withAuth(a=>get(url,{access:'private',...a}));return r?.statusCode===200&&r.stream?await new Response(r.stream).json():null}
function money(value:unknown){if(typeof value==='number'&&Number.isFinite(value))return value;const raw=String(value??'').trim().toLowerCase();if(!raw)return 0;const match=raw.replace(/,/g,'').replace(/₹/g,'').match(/(\d+(?:\.\d+)?)\s*(crore|cr|lakh|lac|k)?/i);if(!match)return 0;const amount=Number(match[1]);if(!Number.isFinite(amount)||amount<=0)return 0;const unit=String(match[2]||'').toLowerCase();if(unit==='crore'||unit==='cr')return amount*10000000;if(unit==='lakh'||unit==='lac')return amount*100000;if(unit==='k')return amount*1000;return amount}
function priceRange(p:any){const min=money(p.minBudget??p.minPrice),max=money(p.maxBudget??p.maxPrice),price=money(p.price);if(min||max)return{min:min||max,max:max||min};return{min:price,max:price}}
function normalise(v:unknown){return String(v??'').toLowerCase().replace(/\s+/g,' ').trim()}
function locationMatch(p:any,w:string){if(!w)return true;return normalise(`${p.title||''} ${p.location||''} ${p.description||''}`).includes(normalise(w))}
function typeMatch(p:any,w:string){if(!w)return true;return normalise(`${p.propertyType||p.type||''} ${p.title||''}`).includes(normalise(w))}
function bhkMatch(p:any,w:string){if(!w||/any/i.test(w))return true;const requested=w.match(/\d+/)?.[0];if(!requested)return true;const nums=String(p.bedrooms||'').match(/\d+(?:\.\d+)?/g)||[];return nums.includes(requested)}
function budgetScore(p:any,budget:number){if(!budget)return 0;const r=priceRange(p);if(!r.min&&!r.max)return 0;if(r.min<=budget&&r.max>=budget)return 40;if(r.min<=budget)return 25;return(r.min-budget)/budget<=0.15?15:0}
function matchScore(p:any,q:any){let score=0;if(q.location)score+=locationMatch(p,q.location)?30:0;if(q.type)score+=typeMatch(p,q.type)?15:0;if(q.bhk)score+=bhkMatch(p,q.bhk)?20:0;score+=budgetScore(p,money(q.budget));if(p.photos?.length)score+=3;if(p.videoUrl)score+=2;return score}
function matches(p:any,q:any){if(!locationMatch(p,q.location)||!typeMatch(p,q.type)||!bhkMatch(p,q.bhk))return false;const budget=money(q.budget);if(!budget)return true;const r=priceRange(p);return !r.min||r.min<=budget||r.min<=budget*1.15}
export default async function handler(req:any,res:any){if(req.method!=='GET'&&req.method!=='POST')return send(res,405,{error:'Method not allowed'});try{const q:any=req.method==='POST'?(req.body||{}):(req.query||{});const result:any=await withAuth(a=>list({prefix:'crm/properties/',...a}));const rows:any[]=(await Promise.all((result.blobs||[]).map(async(b:any)=>{try{return await read(b.url)}catch{return null}}))).filter(Boolean).filter((p:any)=>String(p.status||'Available').toLowerCase()==='available');const matchesList=rows.filter((p:any)=>matches(p,q)).map((p:any)=>({property:p,score:matchScore(p,q)})).sort((a:any,b:any)=>b.score-a.score).slice(0,5).map(({property:p,score}:any,i:number)=>({id:p.id,title:p.title,location:p.location,propertyType:p.propertyType||p.type,price:p.price,minBudget:p.minBudget??null,maxBudget:p.maxBudget??null,area:p.area,bedrooms:p.bedrooms,photos:p.photos||[],videoUrl:p.videoUrl||'',matchScore:score,rank:i+1}));return send(res,200,{ok:true,count:matchesList.length,properties:matchesList})}catch(e){console.error('property match error',e);return send(res,500,{error:'Unable to match properties right now.'})}}
