import { createHmac } from 'node:crypto';

const REVIEW_URL=process.env.GOOGLE_REVIEW_URL||'https://www.google.com/search?q=Anjanay+Heights+Noida';
function header(req:any,name:string){const h=req?.headers;if(h&&typeof h.get==='function')return h.get(name)||'';return h?.[name.toLowerCase()]||h?.[name]||'';}
function sessionToken(){const p=process.env.DASHBOARD_PASSWORD||'';return p?createHmac('sha256',p).update('anjanay-heights-crm-session').digest('hex'):'';}
function cookie(req:any,name:string){const raw=String(header(req,'cookie'));const x=raw.split(';').map((v:string)=>v.trim()).find((v:string)=>v.startsWith(`${name}=`));return x?decodeURIComponent(x.slice(name.length+1)):'';}
function auth(req:any){const p=process.env.DASHBOARD_PASSWORD||'';return Boolean((p&&header(req,'authorization')===`Bearer ${p}`)||(sessionToken()&&cookie(req,'ah_crm_session')===sessionToken()));}
function send(res:any,status:number,body:unknown){return res.status(status).setHeader('Cache-Control','no-store').json(body);}
export default async function handler(req:any,res:any){if(!auth(req))return send(res,401,{error:'Unauthorized'});if(req.method!=='POST')return send(res,405,{error:'Method not allowed'});const b=req.body&&typeof req.body==='object'?req.body:{};const leadId=String(b.leadId||'').trim();const name=String(b.name||'there').trim().slice(0,100);const phone=String(b.phone||'').replace(/\D/g,'');if(!leadId||!phone)return send(res,400,{error:'leadId and phone are required'});const n=phone.length===10?`91${phone}`:phone;if(n.length<11)return send(res,400,{error:'Valid Indian phone is required'});try{const r=await fetch(`${process.env.VERCEL_URL?`https://${process.env.VERCEL_URL}`:''}/api/lead-meta`,{method:'POST',headers:{Authorization:header(req,'authorization')||`Bearer ${process.env.DASHBOARD_PASSWORD||''}`,'Content-Type':'application/json'},body:JSON.stringify({leadId,meta:{reviewRequestedAt:new Date().toISOString(),nextAction:'Follow-up',activity:{action:'Review Request Sent',note:'Genuine Google review request prepared for completed site-visit customer.'}}})});if(!r.ok)throw new Error('Unable to record review request');const message=`Hi ${name}, thank you for visiting with Anjanay Heights. If our team helped you, please share your genuine experience on Google: ${REVIEW_URL} Honest feedback helps future property buyers.`;return send(res,200,{ok:true,reviewUrl:REVIEW_URL,whatsappUrl:`https://wa.me/${n}?text=${encodeURIComponent(message)}`,requestedAt:new Date().toISOString()});}catch(e){console.error('review-request error',e);return send(res,500,{error:'Unable to prepare review request.'});}}
