import { get, head, list, put } from '@vercel/blob';
import { createHmac } from 'node:crypto';
const auths=[...(process.env.VERCEL_OIDC_TOKEN&&process.env.BLOB_STORE_ID?[{oidcToken:process.env.VERCEL_OIDC_TOKEN,storeId:process.env.BLOB_STORE_ID}]:[]),...(process.env.BLOB_READ_WRITE_TOKEN?[{token:process.env.BLOB_READ_WRITE_TOKEN}]:[])];
const send=(res:any,status:number,body:unknown)=>res.status(status).setHeader('Cache-Control','no-store').json(body);
const header=(req:any,n:string)=>req?.headers?.get?n&&req.headers.get(n)||'':req?.headers?.[n.toLowerCase()]||'';
const authorized=(req:any)=>{const p=process.env.DASHBOARD_PASSWORD||'';if(header(req,'authorization')===`Bearer ${p}`)return true;const expected=p?createHmac('sha256',p).update('anjanay-heights-crm-session').digest('hex'):'';return String(header(req,'cookie')||'').split(';').some((x:string)=>x.trim()===`ah_crm_session=${expected}`)};
async function blob<T>(fn:(a:any)=>Promise<T>){let last:any;for(const a of [{},...auths])try{return await fn(a)}catch(e){last=e}throw last}
async function read(url:string){const r:any=await blob(a=>get(url,{access:'private',useCache:false,...a}));return r?.stream?await new Response(r.stream).json():null}
async function collection(path:string){try{const h:any=await blob(a=>head(path,a));return h?.url?await read(h.url):{}}catch{return {}}}
function phone(v:string){const d=String(v||'').replace(/\D/g,'');return d.length===10?`91${d}`:d}
async function sendWhatsApp(to:string,text:string){const token=process.env.WHATSAPP_ACCESS_TOKEN||'';const id=process.env.WHATSAPP_PHONE_NUMBER_ID||'';if(!token||!id||!to)return {sent:false,reason:'WhatsApp credentials or salesperson phone missing'};const version=process.env.WHATSAPP_GRAPH_VERSION||'v23.0';const r=await fetch(`https://graph.facebook.com/${version}/${id}/messages`,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({messaging_product:'whatsapp',to,type:'text',text:{preview_url:false,body:text}})});if(!r.ok)return {sent:false,reason:await r.text()};return {sent:true}}
export async function sendSiteVisitAlert(leadId:string,assignedSalesperson='',assignedPhone='',status='Scheduled'){
 const leads:any=await blob(a=>list({prefix:'leads/',...a}));let lead:any=null;for(const x of leads.blobs||[]){try{const candidate=await read(x.url);if(candidate?.id===leadId){lead=candidate;break}}catch{}}if(!lead)throw new Error('Lead not found');
 const meta=await collection('crm/lead-meta.json');const m=meta[leadId]||{};const agentsRaw=await collection('crm/sales-agents.json');const agents=Array.isArray(agentsRaw)?agentsRaw:Array.isArray(agentsRaw?.agents)?agentsRaw.agents:[];const assigned=String(m.assignedSalesperson||m.assignedAgent||assignedSalesperson||'');const agent=agents.find((a:any)=>String(a.name||'').toLowerCase()===assigned.toLowerCase());const recipient=phone(agent?.phone||assignedPhone||m.assignedPhone||'');const when=m.siteVisitDateTime||'';const visitStatus=m.siteVisitStatus||status||'Scheduled';const text=`📅 ANJANAY HEIGHTS — Site Visit ${visitStatus}\n\nCustomer: ${lead.name||'-'}\n📞 ${lead.phone||'-'}\n📍 ${lead.location||'-'}\n🏠 ${lead.property_type||'Property'}\n${when?`🕒 ${new Date(when).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'})}`:''}\n\nAction: Confirm customer and update Site Visit Desk.\nLead ID: ${leadId}`;const result=await sendWhatsApp(recipient,text);const now=new Date().toISOString();meta[leadId]={...m,siteVisitAlertAt:now,siteVisitAlertStatus:result.sent?'SENT':'FAILED'};await blob(a=>put('crm/lead-meta.json',JSON.stringify(meta),{access:'private',addRandomSuffix:false,allowOverwrite:true,contentType:'application/json',...a}));return {assignedSalesperson:agent?.name||assigned||null,whatsapp:result}}
export default async function handler(req:any,res:any){if(req.method!=='POST')return send(res,405,{error:'Method not allowed'});if(!authorized(req))return send(res,401,{error:'Unauthorized'});try{const b=req.body&&typeof req.body==='object'?req.body:JSON.parse(String(req.body||'{}'));const leadId=String(b.leadId||'').trim();if(!leadId)return send(res,400,{error:'leadId is required'});const result=await sendSiteVisitAlert(leadId,String(b.assignedSalesperson||''),String(b.assignedPhone||''),String(b.siteVisitStatus||'Scheduled'));return send(res,200,{ok:true,leadId,...result})}catch(e){console.error('site visit alert error',e);return send(res,500,{error:'Unable to send site visit alert.'})}}