import { createHmac, timingSafeEqual } from 'node:crypto';
import { get, head, list, put } from '@vercel/blob';

const auths = [
  ...(process.env.VERCEL_OIDC_TOKEN && process.env.BLOB_STORE_ID ? [{ oidcToken: process.env.VERCEL_OIDC_TOKEN, storeId: process.env.BLOB_STORE_ID }] : []),
  ...(process.env.BLOB_READ_WRITE_TOKEN ? [{ token: process.env.BLOB_READ_WRITE_TOKEN }] : []),
];
async function blob<T>(fn:(a:any)=>Promise<T>){let last:any;for(const a of [{},...auths])try{return await fn(a)}catch(e){last=e}throw last}
async function read(url:string){const r:any=await blob(a=>get(url,{access:'private',...a}));return r?.stream?await new Response(r.stream).json():null}
function phone(v:string){const d=String(v||'').replace(/\D/g,'');return d.length===10?`91${d}`:d}
function verify(raw:string,signature:string){const secret=process.env.WHATSAPP_WEBHOOK_SECRET||'';if(!secret)return false;const expected=`sha256=${createHmac('sha256',secret).update(raw).digest('hex')}`;try{return timingSafeEqual(Buffer.from(expected),Buffer.from(signature))}catch{return false}}
async function send(to:string,text:string){const token=process.env.WHATSAPP_ACCESS_TOKEN||'',id=process.env.WHATSAPP_PHONE_NUMBER_ID||'';if(!token||!id)return false;const v=process.env.WHATSAPP_GRAPH_VERSION||'v23.0';const r=await fetch(`https://graph.facebook.com/${v}/${id}/messages`,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({messaging_product:'whatsapp',to,type:'text',text:{preview_url:false,body:text}})});return r.ok}
function parseDateTime(input:string){
  const s=input.trim().toLowerCase().replace(/,/g,' ');
  const dm=s.match(/\b(\d{1,2})[\s\-/]+(jan|feb|mar|apr|may|jun|jul|aug|sep|sept|oct|nov|dec|january|february|march|april|june|july|august|september|october|november|december)\b/);
  const md=s.match(/\b(jan|feb|mar|apr|may|jun|jul|aug|sep|sept|oct|nov|dec|january|february|march|april|june|july|august|september|october|november|december)[\s\-/]+(\d{1,2})\b/);
  const tm=s.match(/\b(\d{1,2})(?::(\d{2}))?\s*(am|pm)\b/) || s.match(/\b(\d{1,2}):(\d{2})\b/);
  if(!tm)return null;
  let day=dm?Number(dm[1]):md?Number(md[2]):0; const mon=dm?dm[2]:md?md[1]:'';
  if(!day||!mon)return null;
  const months:any={jan:0,january:0,feb:1,february:1,mar:2,march:2,apr:3,april:3,may:4,jun:5,june:5,jul:6,july:6,aug:7,august:7,sep:8,sept:8,september:8,oct:9,october:9,nov:10,november:10,dec:11,december:11};
  const month=months[mon]; if(month===undefined)return null;
  let hour=Number(tm[1]); const minute=Number(tm[2]||0); const ap=tm[3];
  if(ap==='pm'&&hour<12)hour+=12;if(ap==='am'&&hour===12)hour=0;if(hour>23||minute>59||day<1||day>31)return null;
  const now=new Date(); const istNow=new Date(now.toLocaleString('en-US',{timeZone:'Asia/Kolkata'})); let year=istNow.getFullYear();
  let d=new Date(year,month,day,hour,minute,0,0);
  if(d.getTime()<istNow.getTime()-3600000)d=new Date(year+1,month,day,hour,minute,0,0);
  if(d.getMonth()!==month||d.getDate()!==day)return null;
  return {date:d.toISOString().slice(0,10),time:`${String(hour).padStart(2,'0')}:${String(minute).padStart(2,'0')}`,display:`${day} ${String(mon).replace(/^./,x=>x.toUpperCase())} at ${hour%12||12}:${String(minute).padStart(2,'0')} ${hour>=12?'PM':'AM'}`};
}
export default async function handler(req:any,res:any){if(req.method==='GET'){const mode=req.query?.['hub.mode'],token=req.query?.['hub.verify_token'],challenge=req.query?.['hub.challenge'];if(mode==='subscribe'&&token&&token===process.env.WHATSAPP_VERIFY_TOKEN)return res.status(200).send(challenge);return res.status(403).send('Forbidden')}
if(req.method!=='POST')return res.status(405).json({error:'Method not allowed'});const raw=typeof req.body==='string'?req.body:JSON.stringify(req.body||{});const sig=req.headers?.['x-hub-signature-256']||'';if(!verify(raw,sig))return res.status(401).json({error:'Invalid signature'});try{const body=JSON.parse(raw);const value=body?.entry?.[0]?.changes?.[0]?.value;const msg=value?.messages?.[0];if(!msg)return res.status(200).json({ok:true,ignored:true});const from=phone(msg.from||'');const text=String(msg.text?.body||'').trim();if(!from)return res.status(200).json({ok:true,ignored:true});const positive=/^(yes|y|site visit|visit|book|interested|haan|ha|हाँ|हां)$/i.test(text.toLowerCase());const requested=parseDateTime(text);if(!positive&&!requested)return res.status(200).json({ok:true,ignored:true});
const result:any=await blob(a=>list({prefix:'leads/',...a}));let lead:any=null;for(const b of result.blobs){try{const l=await read(b.url);if(phone(l?.phone||'')===from){lead=l;break}}catch{}}if(!lead)return res.status(200).json({ok:true,matched:false});let meta:any={};try{const r:any=await blob(a=>list({prefix:'crm/lead-meta.json',...a}));if(r.blobs?.[0])meta=await read(r.blobs[0].url)||{}}catch{}
const now=new Date().toISOString();const old=meta[lead.id]||{};const siteVisit={...(old.siteVisit||{}),status:requested?'Scheduled':'Requested',source:'whatsapp',requestedAt:old.siteVisit?.requestedAt||now};if(requested){siteVisit.date=requested.date;siteVisit.time=requested.time;siteVisit.display=requested.display;siteVisit.confirmedAt=now;}
meta[lead.id]={...old,status:'Site Visit',priority:'Hot',salesStage:'SITE VISIT SCHEDULED',nextAction:requested?'Site Visit Confirmed':'Confirm Site Visit',followUp:now.slice(0,10),siteVisit,whatsappIntent:'SITE_VISIT_REQUESTED',whatsappIntentAt:now,history:[...(old.history||[]),{id:`wa-${Date.now()}`,at:now,action:requested?'WhatsApp Site Visit Scheduled':'WhatsApp YES',note:requested?`Customer requested ${requested.display}.`:'Customer requested a site visit from WhatsApp.'}]};await blob(a=>put('crm/lead-meta.json',JSON.stringify(meta),{access:'private',addRandomSuffix:false,allowOverwrite:true,contentType:'application/json',...a}));
const agentsRaw=await (async()=>{try{const r:any=await blob(a=>list({prefix:'crm/sales-agents.json',...a}));return r.blobs?.[0]?await read(r.blobs[0].url):null}catch{return null}})();const agents=Array.isArray(agentsRaw)?agentsRaw:Array.isArray(agentsRaw?.agents)?agentsRaw.agents:[];const assignedName=String(old.assignedSalesperson||old.assignedAgent||'');const agent=agents.find((a:any)=>String(a.name||'').toLowerCase()===assignedName.toLowerCase());let salespersonAlert=false;if(agent?.phone)salespersonAlert=await send(phone(agent.phone),requested?`🚨 ANJANAY HEIGHTS — SITE VISIT TIME REQUEST\n\n${lead.name||'Customer'} requested ${requested.display}.\n📞 ${lead.phone||'-'}\n📍 ${lead.location||'N/A'}\n🏠 ${lead.property_type||lead.property_name||'Property'}\n\nLead ID: ${lead.id}\nAction: Confirm slot with customer.`:`🚨 ANJANAY HEIGHTS — SITE VISIT REQUEST\n\n${lead.name||'Customer'} replied YES on WhatsApp.\n📞 ${lead.phone||'-'}\n📍 ${lead.location||'N/A'}\n🏠 ${lead.property_type||lead.property_name||'Property'}\n\nLead ID: ${lead.id}\nAction: Contact customer and confirm site visit date/time.`);
const customerMessage=requested?`Great, ${lead.name||'thank you'}! 👍\n\nWe have recorded your preferred site visit time: ${requested.display}.\n\nOur ANJANAY HEIGHTS consultant will confirm the final slot with you shortly.`:`Great, ${lead.name||'thank you'}! 👍\n\nYour site-visit request is registered. Please reply with your preferred date and time, for example: 20 Sep, 11 AM.`;await send(from,customerMessage);return res.status(200).json({ok:true,matched:true,leadId:lead.id,stage:'Site Visit',intent:'SITE_VISIT_REQUESTED',scheduled:Boolean(requested),siteVisit, salespersonAlert})}catch(e){console.error('WhatsApp webhook error',e);return res.status(500).json({error:'Webhook processing failed'})}}