import { createHmac, timingSafeEqual } from 'node:crypto';
import { get, list, put } from '@vercel/blob';

const auths = [
  ...(process.env.VERCEL_OIDC_TOKEN && process.env.BLOB_STORE_ID ? [{ oidcToken: process.env.VERCEL_OIDC_TOKEN, storeId: process.env.BLOB_STORE_ID }] : []),
  ...(process.env.BLOB_READ_WRITE_TOKEN ? [{ token: process.env.BLOB_READ_WRITE_TOKEN }] : []),
];
async function blob<T>(fn:(a:any)=>Promise<T>){let last:any;for(const a of [{},...auths])try{return await fn(a)}catch(e){last=e}throw last}
async function read(url:string){const r:any=await blob(a=>get(url,{access:'private',...a}));return r?.stream?await new Response(r.stream).json():null}
function phone(v:string){const d=String(v||'').replace(/\D/g,'');return d.length===10?`91${d}`:d}
function verify(raw:string,signature:string){const secret=process.env.WHATSAPP_WEBHOOK_SECRET||'';if(!secret)return false;const expected=`sha256=${createHmac('sha256',secret).update(raw).digest('hex')}`;try{return timingSafeEqual(Buffer.from(expected),Buffer.from(signature))}catch{return false}}
async function send(to:string,text:string){const token=process.env.WHATSAPP_ACCESS_TOKEN||'',id=process.env.WHATSAPP_PHONE_NUMBER_ID||'';if(!token||!id)return false;const v=process.env.WHATSAPP_GRAPH_VERSION||'v23.0';const r=await fetch(`https://graph.facebook.com/${v}/${id}/messages`,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({messaging_product:'whatsapp',to,type:'text',text:{preview_url:false,body:text}})});return r.ok}
export default async function handler(req:any,res:any){if(req.method==='GET'){const mode=req.query?.['hub.mode'],token=req.query?.['hub.verify_token'],challenge=req.query?.['hub.challenge'];if(mode==='subscribe'&&token&&token===process.env.WHATSAPP_VERIFY_TOKEN)return res.status(200).send(challenge);return res.status(403).send('Forbidden')}
if(req.method!=='POST')return res.status(405).json({error:'Method not allowed'});const raw=typeof req.body==='string'?req.body:JSON.stringify(req.body||{});const sig=req.headers?.['x-hub-signature-256']||'';if(!verify(raw,sig))return res.status(401).json({error:'Invalid signature'});try{const body=JSON.parse(raw);const value=body?.entry?.[0]?.changes?.[0]?.value;const msg=value?.messages?.[0];if(!msg)return res.status(200).json({ok:true,ignored:true});const from=phone(msg.from||'');const text=String(msg.text?.body||'').trim().toLowerCase();if(!from)return res.status(200).json({ok:true,ignored:true});const positive=/^(yes|y|site visit|visit|book|interested|haan|ha|हाँ|हां)$/i.test(text);if(!positive)return res.status(200).json({ok:true,ignored:true});const result:any=await blob(a=>list({prefix:'leads/',...a}));let lead:any=null;for(const b of result.blobs){try{const l=await read(b.url);if(phone(l?.phone||'')===from){lead=l;break}}catch{}}
if(!lead)return res.status(200).json({ok:true,matched:false});let meta:any={};try{const r:any=await blob(a=>list({prefix:'crm/lead-meta.json',...a}));if(r.blobs?.[0])meta=await read(r.blobs[0].url)||{}}catch{}
const old=meta[lead.id]||{};meta[lead.id]={...old,status:'Site Visit',priority:old.priority||'Hot',nextAction:'Confirm Site Visit',followUp:new Date().toISOString().slice(0,10),siteVisit:{...(old.siteVisit||{}),status:'Requested',source:'whatsapp'},whatsappIntent:'SITE_VISIT_REQUESTED',whatsappIntentAt:new Date().toISOString()};await blob(a=>put('crm/lead-meta.json',JSON.stringify(meta),{access:'private',addRandomSuffix:false,allowOverwrite:true,contentType:'application/json',...a}));await send(from,`Great, ${lead.name||'thank you'}! 👍\n\nYour site-visit request is registered. Our ANJANAY HEIGHTS consultant will contact you shortly to confirm the property, date and time.\n\nPlease keep this WhatsApp chat available for the confirmation.`);return res.status(200).json({ok:true,matched:true,leadId:lead.id,stage:'Site Visit',intent:'SITE_VISIT_REQUESTED'})}catch(e){console.error('WhatsApp webhook error',e);return res.status(500).json({error:'Webhook processing failed'})}}
